"""The method's skills installed into a carrier, and the bookkeeping commands a close runs.

A skill ships as a base in `method/skills/<name>/SKILL.md`; a carrier installs it as the base merged with
its own `LOCAL.md`, so the repository's procedure wins without editing a release file.
"""

from __future__ import annotations

import contextlib
import io
import json
import re
from pathlib import Path
from unittest import mock

from meta.tests.support import Base, bundle, commit, init_repo, make_bundle

B = bundle

BASE = """---
name: "close"
description: "Closes a working session."
allowed-tools: "Bash, Read"
---

# Close

A close is worth what the next session can do with it.

## 1. Every part of what was asked

Re-read every message.

## 2. The documents, true again

Grep the documents.

## 3. The remote

Push only when asked.
"""

LOCAL = """---
description: "Cierra una sesión. Usar cuando se pida \\"cierra la sesión\\"."
---

> The description stays in the owner's language.

## 2. The documents, true again

Grep the documents, and the map in the root file names where each kind lives.

## 3. The remote

## 4. Devices

List the device questions a build can answer.
"""


def run(*argv: str) -> tuple[int, str]:
    out = io.StringIO()
    with contextlib.redirect_stdout(out):
        code = B.main(list(argv))
    return code, out.getvalue()


def a_carrier(root: Path, base: str = BASE) -> tuple[Path, Path]:
    """A carrier repository whose bundle ships the `close` base."""
    repo = init_repo(root / "repo")
    agents = make_bundle(repo)
    (agents / "method/skills/close").mkdir(parents=True)
    (agents / "method/skills/close/SKILL.md").write_text(
        "---\n# Generated by the release build from its original; edit that, never this file.\n" + base[4:])
    B.write_checksums(agents)
    return repo, agents


class Merge(Base):
    def test_a_base_with_no_local_file_installs_as_itself(self) -> None:
        merged = B.merge_skill(BASE, None)

        meta, body = B.read_frontmatter(merged)
        self.assertEqual(meta["name"], "close")
        self.assertEqual(body, B.read_frontmatter(BASE)[1])

    def test_local_frontmatter_wins_key_by_key(self) -> None:
        meta, _ = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertEqual(meta["description"], 'Cierra una sesión. Usar cuando se pida "cierra la sesión".')
        self.assertEqual(meta["allowed-tools"], "Bash, Read")

    def test_a_local_section_replaces_the_base_one_with_its_heading(self) -> None:
        _, body = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertIn("the map in the root file names where each kind lives", body)
        self.assertNotIn("Grep the documents.\n", body)
        self.assertEqual(body.count("## 2. The documents, true again"), 1)

    def test_an_empty_local_section_drops_the_base_one(self) -> None:
        _, body = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertNotIn("## 3. The remote", body)
        self.assertNotIn("Push only when asked", body)

    def test_a_new_local_section_is_appended_after_the_base(self) -> None:
        _, body = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertLess(body.index("## 1. Every part"), body.index("## 4. Devices"))
        self.assertTrue(body.rstrip().endswith("List the device questions a build can answer."))

    def test_the_local_preamble_follows_the_base_preamble(self) -> None:
        _, body = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertLess(body.index("A close is worth"), body.index("stays in the owner's language"))
        self.assertLess(body.index("stays in the owner's language"), body.index("## 1. Every part"))

    def test_a_heading_inside_a_fence_is_not_a_section(self) -> None:
        base = BASE + "\n```markdown\n## 3. The remote\nan example\n```\n"

        _, body = B.read_frontmatter(B.merge_skill(base, "## 9. Extra\n\nMore.\n"))

        self.assertIn("## 3. The remote\nan example", body)

    def test_a_local_name_that_differs_from_the_base_is_refused(self) -> None:
        with self.assertRaises(B.RefusedError):
            B.merge_skill(BASE, '---\nname: "other"\n---\n')


class Install(Base):
    def test_install_writes_the_merged_skill_with_its_banner(self) -> None:
        repo, agents = a_carrier(self.root)
        (repo / ".claude/skills/close").mkdir(parents=True)
        (repo / ".claude/skills/close/LOCAL.md").write_text(LOCAL)

        written = B.install_skills(repo, agents)

        self.assertEqual(written, [".claude/skills/close/SKILL.md"])
        text = (repo / ".claude/skills/close/SKILL.md").read_text()
        self.assertTrue(text.startswith("---\n# " + B.SKILL_BANNER))
        self.assertNotIn("Generated by the release build", text)
        self.assertIn("## 4. Devices", text)

    def test_a_skill_the_repository_wrote_is_not_overwritten(self) -> None:
        repo, agents = a_carrier(self.root)
        (repo / ".claude/skills/close").mkdir(parents=True)
        (repo / ".claude/skills/close/SKILL.md").write_text("---\nname: close\n---\n\nOurs.\n")

        with self.assertRaises(B.RefusedError):
            B.install_skills(repo, agents)
        self.assertIn("Ours.", (repo / ".claude/skills/close/SKILL.md").read_text())

        B.install_skills(repo, agents, force=True)
        self.assertNotIn("Ours.", (repo / ".claude/skills/close/SKILL.md").read_text())

    def test_an_unknown_skill_is_refused(self) -> None:
        repo, agents = a_carrier(self.root)

        with self.assertRaises(B.RefusedError):
            B.install_skills(repo, agents, ["nothing"])

    def test_check_finds_an_installed_skill_edited_by_hand_or_behind_its_base(self) -> None:
        repo, agents = a_carrier(self.root)
        B.install_skills(repo, agents)
        self.assertEqual(B.installed_skill_problems(repo, agents), [])

        installed = repo / ".claude/skills/close/SKILL.md"
        installed.write_text(installed.read_text() + "\nedited\n")
        self.assertEqual(len(B.installed_skill_problems(repo, agents)), 1)

        B.install_skills(repo, agents)
        (repo / ".claude/skills/close/LOCAL.md").write_text("## 9. Later\n\nAdded after the install.\n")
        self.assertEqual(len(B.installed_skill_problems(repo, agents)), 1)

    def test_check_ignores_skills_the_repository_wrote(self) -> None:
        repo, agents = a_carrier(self.root)
        (repo / ".claude/skills/mine").mkdir(parents=True)
        (repo / ".claude/skills/mine/SKILL.md").write_text("---\nname: mine\n---\n\nOurs.\n")

        self.assertEqual(B.installed_skill_problems(repo, agents), [])

    def test_an_installed_skill_whose_base_is_gone_is_a_problem(self) -> None:
        repo, agents = a_carrier(self.root)
        B.install_skills(repo, agents)
        (agents / "method/skills/close/SKILL.md").unlink()

        self.assertEqual(len(B.installed_skill_problems(repo, agents)), 1)

    def test_verify_fails_on_a_stale_installed_skill(self) -> None:
        repo, agents = a_carrier(self.root)
        B.install_skills(repo, agents)
        self.assertEqual(B.verify_problems(agents), [])

        installed = repo / ".claude/skills/close/SKILL.md"
        installed.write_text(installed.read_text() + "\nedited\n")
        self.assertTrue(any("install-skills" in p for p in B.verify_problems(agents)))

    def test_the_command_installs_and_checks(self) -> None:
        repo, agents = a_carrier(self.root)

        code, out = run("install-skills", "--repo", str(repo), "--bundle", str(agents))
        self.assertEqual(code, 0, out)
        code, out = run("install-skills", "--check", "--repo", str(repo), "--bundle", str(agents))
        self.assertEqual(code, 0, out)

        (repo / ".claude/skills/close/LOCAL.md").write_text("## 9. Later\n\nMore.\n")
        code, out = run("install-skills", "--check", "--repo", str(repo), "--bundle", str(agents))
        self.assertEqual(code, 1, out)

    def _two_skills(self, declined: list[str]) -> tuple[Path, Path]:
        repo, agents = a_carrier(self.root)
        (agents / "method/skills/user-walk").mkdir(parents=True)
        (agents / "method/skills/user-walk/SKILL.md").write_text(
            "---\n# Generated by the release build from its original; edit that, never this file.\n"
            'name: "user-walk"\ndescription: "Walks a flow."\n---\n\n# Walk\n\nSteps.\n')
        B.write_checksums(agents)
        entries = ", ".join(f'"{d}"' for d in declined)
        (agents / "carrier.toml").write_text(f"carrier = \"r-abcdef\"\ndeclined = [{entries}]\n")
        return repo, agents

    def test_a_declined_skill_is_skipped_and_said(self) -> None:
        repo, agents = self._two_skills(["skill user-walk: we keep our own"])

        code, out = run("install-skills", "--repo", str(repo), "--bundle", str(agents))

        self.assertEqual(code, 0, out)
        self.assertFalse((repo / ".claude/skills/user-walk").exists())
        self.assertTrue((repo / ".claude/skills/close/SKILL.md").is_file())
        self.assertIn("user-walk", out)
        self.assertIn("declined", out)

    def test_the_forms_that_decline_and_the_ones_that_do_not(self) -> None:
        _, agents = self._two_skills([])

        def declined(*entries: str) -> set[str]:
            quoted = ", ".join(f'"{e}"' for e in entries)
            (agents / "carrier.toml").write_text(f'carrier = "r-abcdef"\ndeclined = [{quoted}]\n')
            return B.declined_skills(agents)

        self.assertEqual(declined("Skill:User-Walk"), {"user-walk"})
        self.assertEqual(declined("skill user-walk"), {"user-walk"})
        self.assertEqual(declined("skills: all of them"), {"*"})
        self.assertEqual(declined("skills"), {"*"})
        self.assertEqual(declined("skill `user-walk`: ours"), {"user-walk"})
        self.assertEqual(declined("skill user-walk, ours"), {"user-walk"})
        with mock.patch.object(B, "read_carrier", return_value={"declined": [3, None, "skill close"]}):
            self.assertEqual(B.declined_skills(agents), {"close"})
        self.assertEqual(declined("skillset foo", "skill user-walker", "skills-extra", "a rule about skill user-walk"),
                         {"user-walker"})

    def test_declining_all_installs_none(self) -> None:
        repo, agents = self._two_skills(["skills: we write our own"])

        self.assertEqual(B.install_skills(repo, agents), [])
        self.assertFalse((repo / ".claude/skills").exists())

    def test_a_declined_skill_already_installed_is_kept_and_flagged(self) -> None:
        repo, agents = self._two_skills([])
        run("install-skills", "--repo", str(repo), "--bundle", str(agents))
        installed = repo / ".claude/skills/user-walk/SKILL.md"
        self.assertTrue(installed.is_file())
        (agents / "carrier.toml").write_text('carrier = "r-abcdef"\ndeclined = ["skill user-walk: ours"]\n')

        code, out = run("install-skills", "--repo", str(repo), "--bundle", str(agents))
        self.assertEqual(code, 0, out)
        self.assertTrue(installed.is_file())

        code, out = run("install-skills", "--check", "--repo", str(repo), "--bundle", str(agents))
        self.assertEqual(code, 0, out)
        self.assertIn("user-walk", out)
        self.assertIn("declined", out)
        self.assertTrue(installed.is_file())
        self.assertEqual(B.installed_skill_problems(repo, agents), [])

    def test_a_declined_skill_that_is_not_installed_is_not_missing(self) -> None:
        repo, agents = self._two_skills(["skill user-walk"])
        run("install-skills", "--repo", str(repo), "--bundle", str(agents))

        code, out = run("install-skills", "--check", "--repo", str(repo), "--bundle", str(agents))

        self.assertEqual(code, 0, out)
        self.assertNotIn("installed though declined", out)


LOG = """# Session changelog

Newest entry below the line.

---

## 2026-01-02 · s-abcdef-111111 — An earlier session

**What.** Something.

---

## Entry format

```
## YYYY-MM-DD · s-<repo6>-<content6> — <one-line title>   (id: `bundle.py id s "<title>"`)
**What.** What changed, concretely.
**Why.** The reason, including the request
that prompted it.
```
"""


LOG_BULLETED = """# Agent log

## How to log

```
### YYYY-MM-DD · s-<repo6>-<content6> — <title>
- **What:** what changed.
- **Why:** the reason.
```

### 2026-01-02 · s-abcdef-111111 — An earlier session

- **What:** something.
"""


class NewEntry(Base):
    def test_the_method_s_entry_format_is_found_in_the_shipped_reference(self) -> None:
        # renaming artifact 5's heading once left the method's format unfound, silently, with every test green
        from meta.tests.support import ROOT
        method = B.section(ROOT / "sources/bundle/method/prompt-context.md", B.CHANGELOG_ARTIFACT)
        self.assertIsNotNone(method)
        self.assertIn("**What.**", B._first_fence(method) or "")

    def test_a_bulleted_format_under_any_heading_keeps_the_log_s_shape(self) -> None:
        # two carriers' logs (2026-10-07): a how-to heading without "format", bold labels in bullets, level-three entries
        template = B.entry_template_text(LOG_BULLETED)
        self.assertIsNotNone(template)
        entry = B.new_entry("A new session", "r-abcdef", "2026-01-03", template, level=B.entry_level(LOG_BULLETED))
        self.assertTrue(entry.startswith("### 2026-01-03 · "), entry)
        self.assertIn("- **What:** <!-- what changed. -->", entry)
        self.assertIn("- **Why:** <!-- the reason. -->", entry)
        text = B.insert_entry(LOG_BULLETED, entry)
        self.assertLess(text.index("A new session"), text.index("An earlier session"))
        self.assertGreater(text.index("A new session"), text.index("```\n\n"))

    def test_the_log_path_is_the_carrier_s_own_field(self) -> None:
        repo, agents = a_carrier(self.root)
        own = B.read_carrier(agents)
        B.write_carrier(agents, {**own, "log": "docs/agent-log.md"})
        log = repo / "docs/agent-log.md"
        log.parent.mkdir(parents=True)
        log.write_text(LOG)

        code, out = run("new", "entry", "T", "--repo", str(repo), "--bundle", str(agents), "--write")

        self.assertEqual(code, 0, out)
        self.assertIn("— T", log.read_text())
        self.assertNotIn("unknown key `log`", "\n".join(B.verify_problems(agents)))

    def test_the_log_s_own_format_is_the_template(self) -> None:
        log = self.root / "log.md"
        log.write_text(LOG)

        entry = B.new_entry("A new session", "r-abcdef", "2026-01-03", B.entry_template(log))

        self.assertTrue(entry.startswith("## 2026-01-03 · " + B.record_id("s", "A new session", "r-abcdef") + " — A new session\n"))
        self.assertIn("**What.** <!-- What changed, concretely. -->", entry)
        self.assertIn("**Why.** <!-- The reason, including the request that prompted it. -->", entry)
        self.assertNotIn("(id:", entry)

    def test_without_a_format_in_the_log_the_method_s_template_is_used(self) -> None:
        log = self.root / "log.md"
        log.write_text("# Log\n")
        agents = make_bundle(self.root)
        (agents / "method/prompt-context.md").write_text(
            "# Context\n\n### " + B.CHANGELOG_ARTIFACT + "\n\n```markdown\n## YYYY-MM-DD · s-x — <t>\n"
            "**What.** What changed.\n**Learned.** General and local.\n```\n")

        entry = B.new_entry("T", "r-abcdef", "2026-01-03", B.entry_template(log, agents))

        self.assertIn("**Learned.** <!-- General and local. -->", entry)

    def test_fields_a_newer_method_added_reach_a_log_with_its_own_format_and_are_named(self) -> None:
        repo, agents = a_carrier(self.root)
        (agents / "method/prompt-context.md").write_text(
            "# Context\n\n### " + B.CHANGELOG_ARTIFACT + "\n\n```markdown\n## YYYY-MM-DD · s-x — <t>\n"
            "**What.** What changed.\n**Why.** The reason.\n**Not verified.** What could not be checked.\n**Learned** General and local.\n```\n")
        log = repo / ".claude/logs/agent-changelog.md"
        log.parent.mkdir(parents=True)
        log.write_text(LOG)

        entry = B.new_entry("T", "r-abcdef", "2026-01-03", B.entry_template(log, agents))

        self.assertIn("**What.** <!-- What changed, concretely. -->", entry)
        self.assertEqual(entry.count("**Why.**"), 1)
        self.assertIn("**Not verified.** <!-- from the method's entry format, which this log's lacks: What could not be checked. -->", entry)
        self.assertLess(entry.index("**Why.**"), entry.index("**Not verified.**"))
        self.assertIn("**Learned** <!-- from the method's", entry)

        code, out = run("new", "entry", "T", "--log", str(log), "--repo", str(repo), "--bundle", str(agents))

        self.assertEqual(code, 0, out)
        said = [line for line in out.split("\n") if "lacks" in line and "<!--" not in line]
        self.assertEqual(len(said), 1, out)
        self.assertIn("**Not verified.** **Learned**;", said[0])

    def test_slash_separated_labels_are_alternatives(self) -> None:
        repo, agents = a_carrier(self.root)
        (agents / "method/prompt-context.md").write_text(
            "# Context\n\n### " + B.CHANGELOG_ARTIFACT + "\n\n```markdown\n## YYYY-MM-DD · s-x — <t>\n"
            "**What.** What changed.\n**Why.** The reason.\n**Not verified.** What could not be checked.\n```\n")
        log = repo / "log.md"
        log.write_text(LOG.replace("**Why.** The reason, including the request\nthat prompted it.",
                                   "**Why.** The reason.\n**Unchecked / Not verified.** What was not checked."))

        result = B.entry_format(log, agents)
        template, added = result[0], result[1]

        self.assertEqual(added, [])
        self.assertEqual(template.count("Not verified"), 1, template)

    def test_a_log_in_another_language_gets_no_english_fields(self) -> None:
        repo, agents = a_carrier(self.root)
        (agents / "method/prompt-context.md").write_text(
            "# Context\n\n### " + B.CHANGELOG_ARTIFACT + "\n\n```markdown\n## YYYY-MM-DD · s-x — <t>\n"
            "**What.** What changed.\n**Why.** The reason.\n**Not verified.** What could not be checked.\n"
            "**Learned.** General and local.\n```\n")
        log = repo / "log.md"
        log.write_text("# Bitácora\n\n---\n\n## 2026-01-02 · s-abcdef-111111 — Otra sesión\n\n**Qué.** Algo.\n\n---\n\n"
                       "## Formato de entrada\n\n```\n## AAAA-MM-DD · s-<repo6>-<contenido6> — <título>\n"
                       "**Qué.** Qué cambió.\n**Por qué.** La razón.\n**Cómo.** El método.\n"
                       "**Aprendido.** Lo general.\n**Pendiente.** Lo que falta.\n```\n")

        code, out = run("new", "entry", "T", "--log", str(log), "--repo", str(repo), "--bundle", str(agents))

        self.assertEqual(code, 0, out)
        fields = [line for line in out.split("\n") if line.startswith("**")]
        for english in ("**What", "**Why", "**Not verified", "**Learned"):
            self.assertFalse([line for line in fields if line.startswith(english)], out)
        for own in ("**Qué.**", "**Por qué.**", "**Cómo.**", "**Aprendido.**", "**Pendiente.**"):
            self.assertIn(own, out)
        said = [line for line in out.split("\n") if "lacks" in line and "<!--" not in line]
        self.assertEqual(len(said), 1, out)
        for name in ("**What.**", "**Why.**", "**Not verified.**", "**Learned.**"):
            self.assertIn(name, said[0])
        self.assertNotIn("from the method's entry format, which this log's lacks:", out)

    def test_the_entry_is_inserted_above_the_newest_one(self) -> None:
        entry = B.new_entry("A new session", "r-abcdef", "2026-01-03", B.entry_template_text(LOG))

        text = B.insert_entry(LOG, entry)

        self.assertLess(text.index("A new session"), text.index("An earlier session"))
        self.assertGreater(text.index("A new session"), text.index("Newest entry below the line"))
        self.assertEqual(text.count("```"), 2)

    def test_a_log_with_no_entry_yet_takes_it_above_its_format(self) -> None:
        first = LOG.split("## 2026-01-02")[0] + "## Entry format" + LOG.split("## Entry format")[1]

        text = B.insert_entry(first, "## 2026-01-03 · s-abcdef-222222 — First\n")

        self.assertLess(text.index("— First"), text.index("## Entry format"))

    def test_the_command_writes_into_the_log(self) -> None:
        repo, agents = a_carrier(self.root)
        log = repo / ".claude/logs/agent-changelog.md"
        log.parent.mkdir(parents=True)
        log.write_text(LOG)

        code, out = run("new", "entry", "A", "new", "session", "--log", str(log), "--repo", str(repo), "--write")

        self.assertEqual(code, 0, out)
        self.assertIn("— A new session", log.read_text())


class Count(Base):
    def test_one_entry_counts_once_however_often_it_names_the_symptom(self) -> None:
        log = self.root / "log.md"
        log.write_text(LOG + "\n## 2026-01-04 · s-abcdef-333333 — Later\n\nThe stash was refused.\nThe stash again.\n")
        (self.root / "ledger.md").write_text("Task 1: Ruling: stash refused\nTask 2: fine\n")

        hits = B.count_mentions("STASH", [log, self.root / "ledger.md"])

        self.assertEqual(len(hits), 2)
        self.assertEqual(hits[0].where, "2026-01-04 · s-abcdef-333333 — Later")
        self.assertEqual(hits[1].where, "line 1")

    def test_the_command_prints_the_count(self) -> None:
        log = self.root / "log.md"
        log.write_text(LOG)

        code, out = run("count", "earlier", str(log))

        self.assertEqual(code, 0, out)
        self.assertIn("1 entries", out)

    def test_a_line_repeated_word_for_word_is_counted_and_flagged_never_subtracted(self) -> None:
        # A friction recorded each time in the same words was folded as a copy, and undercounted.
        log = self.root / "log.md"
        same = "- The stash was refused by the sandbox."
        log.write_text(LOG + f"\n## 2026-01-04 · s-abcdef-333333 — Later\n\n{same}\n"
                             f"\n## 2026-01-05 · s-abcdef-444444 — Close\n\n  {same.upper()}  \n"
                             f"\n## 2026-01-06 · s-abcdef-555555 — Again\n\n{same}\n")

        counted, repeats = B.count_report("stash", [log])
        code, out = run("count", "stash", str(log))

        self.assertEqual(len(counted), 3)
        self.assertEqual([m.where for m in repeats], ["2026-01-05 · s-abcdef-444444 — Close", "2026-01-06 · s-abcdef-555555 — Again"])
        self.assertEqual(len(B.count_mentions("stash", [log])), 3)
        self.assertIn("3 entries", out)
        self.assertIn("2 of them repeat an earlier line word for word", out)
        self.assertIn("a copy or a recurrence", out)
        self.assertNotIn("folded", out)
        self.assertIn("not incidents", out)
        helps = [line for line in B._parser().format_help().split("\n") if re.sub(r"\x1b\[[0-9;]*m", "", line.strip()).startswith("count ")]
        self.assertIn("not incidents", " ".join(helps))


class MemoryDiff(Base):
    def test_each_memory_says_whether_the_repository_holds_what_it_names(self) -> None:
        repo = init_repo(self.root / "repo")
        (repo / "notes.md").write_text("Start the emulator with `-gpu swiftshader`;\nthe hardware renderer crashes it on this machine.\n")
        commit(repo)
        memory = self.root / "memory"
        memory.mkdir()
        (memory / "MEMORY.md").write_text("- index\n")
        (memory / "gpu.md").write_text('---\nname: "gpu"\ndescription: "the emulator needs the software GPU"\n---\n\n'
                                       "Start it with `-gpu swiftshader`: the hardware renderer crashes it.\n")
        (memory / "lone.md").write_text('---\nname: "lone"\ndescription: "only here"\n---\n\nRun `make wobble`.\n')
        (memory / "prose.md").write_text('---\nname: "prose"\ndescription: "scale"\n---\n\nOne scale.\n')
        (repo / ".agents").mkdir()
        (repo / ".agents/README.md").write_text("The bundle says `make wobble` too.\n")
        commit(repo)

        found = {m.name: m for m in B.memory_report(memory, repo)}

        self.assertEqual(sorted(found), ["gpu", "lone", "prose"])
        self.assertEqual(found["gpu"].found_in, ["notes.md"])
        self.assertEqual(found["lone"].found_in, [])
        self.assertTrue(found["lone"].searched)
        self.assertFalse(found["prose"].searched)

    def test_a_shared_code_span_alone_is_partly_held_and_names_what_matched(self) -> None:
        # A rule that names the gate was counted as held because the gate's name appears in the repository.
        repo = init_repo(self.root / "repo")
        (repo / "CONTRIBUTING.md").write_text("# Contributing\n\nBefore you push, run `make gate`: it runs the tests and the linter.\n")
        commit(repo)
        memory = self.root / "memory"
        memory.mkdir()
        (memory / "trailer.md").write_text(
            '---\nname: "trailer"\ndescription: "no attribution trailer"\n---\n\n'
            "Never add an attribution trailer to a commit message; run `make gate` before every commit.\n\n"
            "**Why:** the owner is the sole author.\n")

        found = B.memory_report(memory, repo)[0]

        self.assertEqual((found.found_in, found.partly, found.matched), ([], ["CONTRIBUTING.md"], ["make gate"]))
        code, out = run("memory-diff", "--repo", str(repo), "--memory", str(memory))
        self.assertEqual(code, 0, out)
        self.assertIn("partly held", out)
        self.assertIn("make gate", out)

        (repo / "AGENTS.md").write_text("# Rules\n\n- Commits carry no attribution trailer in their message.\n- Other rules.\n")
        commit(repo)

        found = B.memory_report(memory, repo)[0]

        self.assertEqual((found.found_in, found.partly), (["AGENTS.md"], []))

    def test_a_short_rule_is_not_held_by_a_manifest_or_by_three_shared_words(self) -> None:
        # A package manifest whose script names matched held "Run the lint and test gate before any commit".
        repo = init_repo(self.root / "repo")
        (repo / "package.json").write_text('{\n  "scripts": {\n    "lint": "eslint .",\n    "test": "jest",\n'
                                           '    "gate": "npm run lint && npm run test",\n    "commit": "cz"\n  }\n}\n')
        (repo / "package-lock.json").write_text('{"lint": 1, "test": 2, "gate": 3, "commit": 4}\n')
        (repo / "README.md").write_text("# Scripts\n\nThe lint, test and gate scripts live in the manifest.\n")
        commit(repo)
        memory = self.root / "memory"
        memory.mkdir()
        (memory / "gate.md").write_text('---\nname: "gate"\ndescription: "Run the lint and test gate before any commit"\n---\n\n'
                                        "Run the lint and test gate before any commit.\n")

        found = B.memory_report(memory, repo)[0]

        self.assertEqual(found.found_in, [])
        self.assertTrue(found.searched)

        (repo / "CONTRIBUTING.md").write_text("# Contributing\n\n- Run the lint and the test gate before every commit.\n")
        commit(repo)

        self.assertEqual(B.memory_report(memory, repo)[0].found_in, ["CONTRIBUTING.md"])

    def test_a_memory_with_nested_frontmatter_is_read(self) -> None:
        repo = init_repo(self.root / "repo")
        commit(repo)
        memory = self.root / "memory"
        memory.mkdir()
        (memory / "nested.md").write_text("---\nname: nested\ndescription: with metadata\nmetadata:\n  type: feedback\n---\n\nBody.\n")

        found = B.memory_report(memory, repo)

        self.assertEqual([(m.name, m.description) for m in found], [("nested", "with metadata")])

    def test_the_memory_folder_is_named_after_the_repository_path(self) -> None:
        self.assertEqual(B.memory_dir(Path("/a/b.c/d_e"), Path("/h")), Path("/h/.claude/projects/-a-b-c-d-e/memory"))


def _transcript(folder: Path, session: str, records: list[object]) -> None:
    """A synthetic session transcript, one JSON record per line, as the assistant's host writes them."""
    folder.mkdir(parents=True, exist_ok=True)
    (folder / f"{session}.jsonl").write_text("".join((r if isinstance(r, str) else json.dumps(r)) + "\n" for r in records))


def _user(when: str, content: object, **extra: object) -> dict:
    return {"type": "user", "timestamp": when, "message": {"role": "user", "content": content}, **extra}


def _tool(when: str, name: str, payload: dict) -> dict:
    return {"type": "assistant", "timestamp": when,
            "message": {"content": [{"type": "text", "text": "Working."}, {"type": "tool_use", "id": "t", "name": name, "input": payload}]}}


QUESTION = {"question": "Which way?", "options": [{"label": "Fast"}, {"label": "Safe"}], "multiSelect": False}


class Turns(Base):
    """What the human said, read from synthetic transcripts: never a real one, which carries identity."""

    def sessions(self) -> Path:
        folder = self.root / "projects/one"
        _transcript(folder, "aaaaaaaa-1111", [
            _user("2026-03-01T09:00:00.000Z", "an old request"),
            _user("2026-03-02T10:00:00.000Z", "fix the gate, please"),
            _user("2026-03-02T10:00:01.000Z", "<system-reminder>not the human</system-reminder>"),
            _user("2026-03-02T10:00:02.000Z", "expanded skill text", isMeta=True),
            _user("2026-03-02T10:00:03.000Z", "a delegated agent's prompt", isSidechain=True),
            _user("2026-03-02T10:00:04.000Z", [{"type": "tool_result", "tool_use_id": "t", "content": "ok"}]),
            _user("2026-03-02T10:00:05.000Z", "<task-notification>a background task ended</task-notification>",
                  origin={"kind": "task-notification"}),
            _user("2026-03-02T10:00:06.000Z", [{"type": "text", "text": "<ide_opened_file>the editor's file</ide_opened_file>"},
                                               {"type": "text", "text": "look at this file"}], origin={"kind": "human"}),
            "{not json",
            {"type": "attachment", "timestamp": "2026-03-02T10:01:00.000Z", "attachment": {"type": "queued_command", "prompt": "and the docs too"}},
            {"type": "attachment", "timestamp": "2026-03-02T10:01:01.000Z",
             "attachment": {"type": "queued_command", "prompt": "<agent-message from=x>another agent</agent-message>", "commandMode": "prompt"}},
            _tool("2026-03-02T10:02:00.000Z", "AskUserQuestion", {"questions": [QUESTION]}),
            _user("2026-03-02T10:03:00.000Z", [{"type": "tool_result", "tool_use_id": "t", "content": "answered"}],
                  toolUseResult={"questions": [QUESTION], "answers": {"Which way?": "neither: measure first"}}),
            _user("2026-03-02T10:04:00.000Z", [{"type": "tool_result", "tool_use_id": "t", "content": "answered"}],
                  toolUseResult={"questions": [QUESTION], "answers": {"Which way?": "Safe"}}),
            _tool("2026-03-02T10:05:00.000Z", "Skill", {"skill": "close"}),
        ])
        _transcript(self.root / "projects/two", "bbbbbbbb-2222", [_user("2026-03-01T08:00:00.000Z", "the earlier session")])
        return folder

    def test_the_human_s_turns_newest_last_and_free_text_marked(self) -> None:
        folder = self.sessions()

        lines = B.turns_report([folder, self.root / "projects/two"], since="2026-03-02")
        text = "\n".join(lines)

        self.assertNotIn("an old request", text)
        self.assertNotIn("the earlier session", text)
        for absent in ("not the human", "expanded skill", "delegated agent", "answered", "Working.", "background task",
                       "editor's file", "another agent"):
            self.assertNotIn(absent, text)
        order = ["human: fix the gate, please", "human: look at this file", "human, mid-turn: and the docs too", "Q: Which way? [Fast | Safe]",
                 "A: neither: measure first  (free text)", "A: Safe", "skill: close"]
        self.assertEqual([next(i for i, line in enumerate(lines) if s in line) for s in order],
                         sorted(next(i for i, line in enumerate(lines) if s in line) for s in order))
        self.assertNotIn("A: Safe  (free text)", text)

        everything = B.turns_report([folder, self.root / "projects/two"])
        self.assertLess(everything.index(next(x for x in everything if "the earlier session" in x)),
                        everything.index(next(x for x in everything if "fix the gate" in x)))

    def test_the_default_folders_are_the_repository_s_and_its_worktrees(self) -> None:
        repo = init_repo(self.root / "my.repo")
        commit(repo)
        home = self.root / "home"
        projects = home / ".claude/projects"
        encoded = re.sub(r"[^A-Za-z0-9]", "-", repo.as_posix())
        for name in (encoded, encoded + "--claude-worktrees-side", encoded + "-other", "-elsewhere"):
            (projects / name).mkdir(parents=True)

        found = B.transcript_dirs(repo, home)

        self.assertEqual([p.name for p in found], [encoded, encoded + "--claude-worktrees-side"])

    def test_the_command_prints_them(self) -> None:
        folder = self.sessions()

        code, out = run("turns", "--since", "2026-03-02", str(folder))

        self.assertEqual(code, 0, out)
        self.assertIn("human: fix the gate, please", out)
        self.assertIn("(free text)", out)


class TriggerEval(Base):
    """The trigger eval reads a session's stream and stops at its first tool call."""

    def setUp(self) -> None:
        super().setUp()
        from meta.tests.support import ROOT, _load
        self.T = _load("trigger", ROOT / "evals/skills/trigger.py")

    def test_the_first_tool_call_decides(self) -> None:
        skill = '{"type":"assistant","message":{"content":[{"type":"tool_use","name":"Skill","input":{"skill":"close"}}]}}'
        other = '{"type":"assistant","message":{"content":[{"type":"tool_use","name":"Read","input":{}}]}}'
        text = '{"type":"assistant","message":{"content":[{"type":"text","text":"hi"}]}}'

        self.assertEqual(self.T.first_call([text, skill, other]), ("Skill", "close"))
        self.assertEqual(self.T.first_call([text, other, skill]), ("Read", ""))
        self.assertEqual(self.T.first_call([text, "not json"]), (None, ""))

    def test_rates_are_judged_against_their_thresholds(self) -> None:
        results = [{"expect": True, "fired": True}] * 8 + [{"expect": True, "fired": False}] * 2 \
            + [{"expect": False, "fired": False}] * 9 + [{"expect": False, "fired": True}]

        verdict = self.T.verdict(results)

        self.assertEqual((verdict["fire"], verdict["misfire"]), (0.8, 0.1))
        self.assertTrue(verdict["passed"])
        self.assertFalse(self.T.verdict(results + [{"expect": False, "fired": True}])["passed"])

    def test_a_lenient_gate_counts_a_fire_after_reads_on_both_sides(self) -> None:
        # a skill whose requests point at material a session reads first (decision-review, stage 2b)
        looked = [{"expect": True, "fired": False, "lenient": True}] * 8 + [{"expect": True, "fired": False, "lenient": False}] * 2
        quiet = [{"expect": False, "fired": False, "lenient": False}] * 10
        self.assertFalse(self.T.verdict(looked + quiet)["passed"])
        lenient = self.T.verdict(looked + quiet, gate="lenient")
        self.assertTrue(lenient["passed"])
        self.assertEqual(lenient["gate"], "lenient")
        # a near miss that fires after a look is a misfire under the lenient gate
        late = [{"expect": False, "fired": False, "lenient": True}] * 2
        self.assertFalse(self.T.verdict(looked + quiet[:8] + late, gate="lenient")["passed"])

    def test_a_read_with_git_dash_c_is_a_read(self) -> None:
        allow = lambda command: self.T.hook_decision({"tool_name": "Bash", "tool_input": {"command": command}})  # noqa: E731
        self.assertEqual(allow("git -C /tmp/x status --short -uall"), 0)
        self.assertEqual(allow("git -C /tmp/x log --oneline -5"), 0)
        self.assertEqual(allow("git -C /tmp/x push"), 2)
        self.assertEqual(allow("git -C /tmp/x branch new"), 2)

    @staticmethod
    def call(name: str, skill: str = "") -> str:
        block = {"type": "tool_use", "name": name, "input": {"skill": skill} if skill else {}}
        return json.dumps({"type": "assistant", "message": {"content": [block]}})

    def test_the_lenient_metric_counts_a_fire_in_the_first_three_calls_before_any_write(self) -> None:
        read, skill, write = self.call("Read"), self.call("Skill", "close"), self.call("Edit")

        self.assertEqual(self.T.judge(self.T.tool_calls([read, skill]), "close"), {"strict": False, "lenient": True})
        self.assertEqual(self.T.judge(self.T.tool_calls([skill]), "plugin:close"[7:]), {"strict": True, "lenient": True})
        self.assertEqual(self.T.judge(self.T.tool_calls([write, skill]), "close"), {"strict": False, "lenient": False})
        self.assertEqual(self.T.judge(self.T.tool_calls([read] * 5 + [skill]), "close"),
                         {"strict": False, "lenient": False})
        self.assertTrue(self.T.judge(self.T.tool_calls([read] * 4 + [skill]), "close")["lenient"])
        # any tool the eval refuses ends the window, a connector's as much as an edit
        self.assertFalse(self.T.judge(self.T.tool_calls([self.call("mcp__tracker__create"), skill]), "close")["lenient"])

    def test_read_only_shell_commands_run_and_everything_else_is_refused(self) -> None:
        allow = lambda tool, inp=None: self.T.hook_decision({"tool_name": tool, "tool_input": inp or {}})  # noqa: E731
        for command in ("ls docs", "git status", "git log --oneline -5", "cat docs/spec.md", "git diff", "head -20 src/cart.py"):
            self.assertEqual(allow("Bash", {"command": command}), 0, command)
        for command in ("git push origin main", "git commit -m x", "rm -rf .", "ls; rm x", "cat a > b",
                        "echo $(whoami)", "git status && git push", "curl http://x", "python3 -c 1"):
            self.assertEqual(allow("Bash", {"command": command}), 2, command)
        self.assertEqual(allow("Read"), 0)
        self.assertEqual(allow("mcp__tracker__create_issue"), 2)
        # commands of an allowed reader that write or run something (a review on 2026-10-07)
        for command in ("find . -fprintf /tmp/x %p", "find . -fprint0 /tmp/x", "find . -fls /tmp/x", "find . -okdir rm {} +",
                        "find . -execdir rm {} +", "rg --pre=sh x", "rg --pre sh x", "tree -o /tmp/x", "git branch new",
                        "git branch -D main", "git branch -m a b"):
            self.assertEqual(allow("Bash", {"command": command}), 2, command)
        for command in ("find . -name '*.md'", "git branch", "git branch --list", "git branch -a", "rg -n spec docs"):
            self.assertEqual(allow("Bash", {"command": command}), 0, command)
        # compound reads run, as sessions look with them (stage 2, 2026-10-07): every part must read
        for command in ("git status --short && find . -name x", "git log --oneline -5 2>&1 | head",
                        'grep -rniE "upload|File\\(|multipart" src docs', "ls -R src | head -100 && grep -rn x src",
                        "git status --short | head; ls", "echo --- && git log --oneline -3", "ls docs 2>/dev/null || ls",
                        "git log -5 2>&1; git remote -v; git stash list", "ls .x 2>/dev/null; ls", "grep -rn x src | sort",
                        "ls >/dev/null && ls"):
            self.assertEqual(allow("Bash", {"command": command}), 0, command)
        for command in ("ls && rm x", "git status | sh", "find . | xargs rm", "cat a 2> b", "ls & rm x", "ls\nrm x",
                        "git log > out", "echo `id`", "ls <(rm x)", "ls 'unclosed", "ls &&", "git status && git push",
                        "grep x a | sort -o b", "git remote add o u", "git stash", "git stash pop", "ls 2>&1 > out"):
            self.assertEqual(allow("Bash", {"command": command}), 2, command)

    def test_what_the_shell_would_expand_or_run_is_refused(self) -> None:
        # every command here was accepted by the first compound classifier (a review on 2026-10-07)
        allow = lambda command: self.T.hook_decision({"tool_name": "Bash", "tool_input": {"command": command}})  # noqa: E731
        for command in ("find . -$Zdelete", "find . -{delete,x}", "find . $'-delete'", "echo ${A:=-delete}; find . $A",
                        "git log --out{put,}=f", "echo a#b ; rm x", "echo a#b;rm x", "sort --out=f x", "sort --outp=f x",
                        "git log --out=f", "git diff --ou=f", "rg --hostname-bin=sh x", "sort -S 1 --compress-program=sh x",
                        "rg -z x", "rg -nz x", "rg --search-zip x", "git diff --ext-diff", "git diff --textconv",
                        "git show --ext-diff", "tail -f x", "tail -F x", 'grep "$HOME" x', "ls \\$(id)",
                        "sort --o=f x", "cat a 2>&1>f", "ls >/dev/null>f", "ls 2>/dev/nullx", "ls >| f", "ls &",
                        "tail --follow x", "tail --follow=name x", "tail --retry x", "ls\0; rm x"):
            self.assertEqual(allow(command), 2, command)
        for command in ("find . -name '*.md'", "wc -l docs/*.md", "grep -rn 'a$' src", 'grep -E "a|b(c)" src',
                        "git status --short && git log --oneline -5 2>&1; git branch -a", "grep -z x f",
                        "cat 'a b.txt'", "ls docs\\ x", "ls -fl", "sort -fu x", "find . -follow -name x"):
            self.assertEqual(allow(command), 0, command)

    def test_a_long_shell_command_is_judged_whole(self) -> None:
        long = "git status --short && " + " && ".join(f"ls dir{i}" for i in range(40))
        bash = json.dumps({"type": "assistant", "message": {"content": [{"type": "tool_use", "name": "Bash",
                           "input": {"command": long}}]}})
        self.assertEqual(self.T.tool_calls([bash]), [("Bash", long)])
        self.assertTrue(self.T.allowed(("Bash", long)))

    def test_the_refusing_hook_fails_closed(self) -> None:
        import subprocess
        hook = self.T.deny_hook_settings(None)["hooks"]["PreToolUse"][-1]["hooks"][0]["command"]
        for payload in ("not json", "[]", '{"tool_name": 3, "tool_input": "x"}'):
            ran = subprocess.run(hook, shell=True, input=payload, capture_output=True, text=True)
            self.assertEqual(ran.returncode, 2, payload)

    def test_a_shell_call_keeps_its_command_so_a_capture_can_be_read(self) -> None:
        bash = json.dumps({"type": "assistant", "message": {"content": [{"type": "tool_use", "name": "Bash",
                           "input": {"command": "ls docs"}}]}})
        self.assertEqual(self.T.tool_calls([bash]), [("Bash", "ls docs")])
        # a read-only command does not end the window: the skill may still come after it
        self.assertFalse(self.T.should_stop(self.T.tool_calls([bash]), "close"))
        self.assertTrue(self.T.judge(self.T.tool_calls([bash, self.call("Skill", "close")]), "close")["lenient"])

    def test_a_session_is_stopped_at_a_fire_a_refused_call_or_the_window(self) -> None:
        read, skill, bash = self.call("Read"), self.call("Skill", "close"), self.call("Bash")
        stop = lambda lines: self.T.should_stop(self.T.tool_calls(lines), "close")  # noqa: E731
        self.assertFalse(stop([read, read]))
        self.assertTrue(stop([read, skill]))
        self.assertTrue(stop([bash]))
        self.assertTrue(stop([self.call("mcp__tracker__create")]))
        self.assertTrue(stop([read] * 5))

    def test_reading_the_skill_file_is_a_fire_and_a_router_skill_is_looked_past(self) -> None:
        own = json.dumps({"type": "assistant", "message": {"content": [{"type": "tool_use", "name": "Read",
                          "input": {"file_path": "/tmp/w/.claude/skills/close/SKILL.md"}}]}})
        other = json.dumps({"type": "assistant", "message": {"content": [{"type": "tool_use", "name": "Read",
                            "input": {"file_path": "/tmp/w/.claude/skills/closer/SKILL.md"}}]}})
        router, todo, skill = self.call("Skill", "kit:using-kit"), self.call("TodoWrite"), self.call("Skill", "close")

        self.assertTrue(self.T.judge(self.T.tool_calls([own]), "close")["strict"])
        self.assertFalse(self.T.judge(self.T.tool_calls([other]), "close")["lenient"])
        verdict = self.T.judge(self.T.tool_calls([router, todo, skill]), "close", routers=("using-kit",))
        self.assertEqual(verdict, {"strict": False, "lenient": True, "routed": True})
        self.assertFalse(self.T.judge(self.T.tool_calls([router, self.call("Grep"), skill]), "close",
                                      routers=("using-kit",))["routed"])

    def test_a_session_that_never_ran_is_an_error_never_a_quiet_answer(self) -> None:
        init = json.dumps({"type": "system", "subtype": "init", "model": "m", "tools": ["Read"], "skills": ["close"]})
        failed = json.dumps({"type": "result", "is_error": True, "result": "usage limit reached"})
        quiet = json.dumps({"type": "result", "is_error": False, "result": "done"})

        self.assertIsNone(self.T.session_error([init, self.call("Read")]))
        self.assertIsNone(self.T.session_error([init, quiet]))
        self.assertIn("usage limit", self.T.session_error([init, failed]))
        self.assertIn("no result", self.T.session_error([init]))
        self.assertIn("no init", self.T.session_error([]))
        self.assertEqual(self.T.session_info([init])["model"], "m")

        rows = [{"expect": True, "fired": True}] * 4 + [{"expect": False, "fired": False}] * 4 \
            + [{"expect": False, "fired": False, "error": "usage limit"}] * 3
        verdict = self.T.verdict(rows)
        self.assertEqual((verdict["cases"], verdict["errors"]), (8, 3))

    def test_intervals_owner_cases_and_captures_are_reported(self) -> None:
        lo, hi = self.T.wilson(8, 10)
        self.assertAlmostEqual(lo, 0.49, places=2)
        self.assertAlmostEqual(hi, 0.943, places=2)
        self.assertEqual(self.T.wilson(0, 0), (0.0, 1.0))

        results = [{"request": "close it", "expect": True, "owner": True, "fired": False, "lenient": False,
                    "first_call": "Skill:wrap-up"}] * 3 + [{"request": "push", "expect": False, "fired": False,
                                                            "lenient": False, "first_call": "Bash"}] * 3
        verdict = self.T.verdict(results)
        self.assertEqual(verdict["owner_fire"], 0.0)
        self.assertFalse(verdict["passed"])
        self.assertEqual(len(verdict["fire_interval"]), 2)
        self.assertEqual(self.T.captures(results)["close it"], {"Skill:wrap-up": 3})

    def test_a_canary_that_did_not_fire_makes_the_run_invalid(self) -> None:
        clear = [{"expect": True, "fired": True}] * 4 + [{"expect": False, "fired": False}] * 4
        self.assertTrue(self.T.verdict(clear + [{"expect": True, "canary": True, "fired": True}])["valid"])
        broken = self.T.verdict(clear + [{"expect": True, "canary": True, "fired": False}])
        self.assertFalse(broken["valid"])
        self.assertFalse(broken["passed"])
        self.assertEqual(broken["cases"], 8)

    def test_ambiguous_cases_are_reported_apart_and_never_decide(self) -> None:
        clear = [{"expect": True, "fired": True, "lenient": True}] * 4 + [{"expect": False, "fired": False}] * 4
        unsure = [{"expect": True, "ambiguous": True, "fired": False}] * 3 + [{"expect": False, "ambiguous": True, "fired": True}]
        verdict = self.T.verdict(clear + unsure)
        self.assertTrue(verdict["passed"])
        self.assertEqual((verdict["fire"], verdict["misfire"], verdict["cases"]), (1.0, 0.0, 8))
        self.assertEqual(verdict["ambiguous"], {"cases": 4, "agreed": 0})

    def test_refused_tools_stay_visible_and_are_denied_by_a_hook(self) -> None:
        settings = self.T.deny_hook_settings({"permissions": {"allow": ["Read"]},
                                              "hooks": {"PreToolUse": [{"matcher": "Read", "hooks": []}]}})

        self.assertEqual(settings["permissions"], {"allow": ["Read"]})
        added = settings["hooks"]["PreToolUse"][-1]
        self.assertEqual(added["matcher"], "*")  # refused unless allowed: a connector's tools included
        import subprocess
        for tool, inp, code in (("Read", {}, 0), ("Skill", {}, 0), ("Bash", {"command": "git push"}, 2),
                                ("Bash", {"command": "git status"}, 0), ("Edit", {}, 2),
                                ("mcp__tracker__create_issue", {}, 2)):
            ran = subprocess.run(added["hooks"][0]["command"], shell=True,
                                 input=json.dumps({"tool_name": tool, "tool_input": inp}), capture_output=True, text=True)
            self.assertEqual(ran.returncode, code, tool)
        self.assertEqual(len(settings["hooks"]["PreToolUse"]), 2)
        self.assertNotIn("--disallowedTools", self.T.command("claude", "a request"))
