"""The method's skills installed into a carrier, and the bookkeeping commands a close runs.

A skill ships as a base in `method/skills/<name>/SKILL.md`; a carrier installs it as the base merged with
its own `LOCAL.md`, so the repository's procedure wins without editing a release file.
"""

from __future__ import annotations

import contextlib
import io
from pathlib import Path

from meta.tests.support import Base, bundle, commit, init_repo, make_bundle

B = bundle

BASE = """---
name: "close"
description: "Closes a working session."
allowed-tools: "Bash, Read"
---

# Close

A close is worth what the next session can do with it.

## 1. Every part of what was asked

Re-read every message.

## 2. The documents, true again

Grep the documents.

## 3. The remote

Push only when asked.
"""

LOCAL = """---
description: "Cierra una sesión. Usar cuando se pida \\"cierra la sesión\\"."
---

> The description stays in the owner's language.

## 2. The documents, true again

Grep the documents, and the map in the root file names where each kind lives.

## 3. The remote

## 4. Devices

List the device questions a build can answer.
"""


def run(*argv: str) -> tuple[int, str]:
    out = io.StringIO()
    with contextlib.redirect_stdout(out):
        code = B.main(list(argv))
    return code, out.getvalue()


def a_carrier(root: Path, base: str = BASE) -> tuple[Path, Path]:
    """A carrier repository whose bundle ships the `close` base."""
    repo = init_repo(root / "repo")
    agents = make_bundle(repo)
    (agents / "method/skills/close").mkdir(parents=True)
    (agents / "method/skills/close/SKILL.md").write_text(
        "---\n# Generated by the release build from its original; edit that, never this file.\n" + base[4:])
    B.write_checksums(agents)
    return repo, agents


class Merge(Base):
    def test_a_base_with_no_local_file_installs_as_itself(self) -> None:
        merged = B.merge_skill(BASE, None)

        meta, body = B.read_frontmatter(merged)
        self.assertEqual(meta["name"], "close")
        self.assertEqual(body, B.read_frontmatter(BASE)[1])

    def test_local_frontmatter_wins_key_by_key(self) -> None:
        meta, _ = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertEqual(meta["description"], 'Cierra una sesión. Usar cuando se pida "cierra la sesión".')
        self.assertEqual(meta["allowed-tools"], "Bash, Read")

    def test_a_local_section_replaces_the_base_one_with_its_heading(self) -> None:
        _, body = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertIn("the map in the root file names where each kind lives", body)
        self.assertNotIn("Grep the documents.\n", body)
        self.assertEqual(body.count("## 2. The documents, true again"), 1)

    def test_an_empty_local_section_drops_the_base_one(self) -> None:
        _, body = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertNotIn("## 3. The remote", body)
        self.assertNotIn("Push only when asked", body)

    def test_a_new_local_section_is_appended_after_the_base(self) -> None:
        _, body = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertLess(body.index("## 1. Every part"), body.index("## 4. Devices"))
        self.assertTrue(body.rstrip().endswith("List the device questions a build can answer."))

    def test_the_local_preamble_follows_the_base_preamble(self) -> None:
        _, body = B.read_frontmatter(B.merge_skill(BASE, LOCAL))

        self.assertLess(body.index("A close is worth"), body.index("stays in the owner's language"))
        self.assertLess(body.index("stays in the owner's language"), body.index("## 1. Every part"))

    def test_a_heading_inside_a_fence_is_not_a_section(self) -> None:
        base = BASE + "\n```markdown\n## 3. The remote\nan example\n```\n"

        _, body = B.read_frontmatter(B.merge_skill(base, "## 9. Extra\n\nMore.\n"))

        self.assertIn("## 3. The remote\nan example", body)

    def test_a_local_name_that_differs_from_the_base_is_refused(self) -> None:
        with self.assertRaises(B.RefusedError):
            B.merge_skill(BASE, '---\nname: "other"\n---\n')


class Install(Base):
    def test_install_writes_the_merged_skill_with_its_banner(self) -> None:
        repo, agents = a_carrier(self.root)
        (repo / ".claude/skills/close").mkdir(parents=True)
        (repo / ".claude/skills/close/LOCAL.md").write_text(LOCAL)

        written = B.install_skills(repo, agents)

        self.assertEqual(written, [".claude/skills/close/SKILL.md"])
        text = (repo / ".claude/skills/close/SKILL.md").read_text()
        self.assertTrue(text.startswith("---\n# " + B.SKILL_BANNER))
        self.assertNotIn("Generated by the release build", text)
        self.assertIn("## 4. Devices", text)

    def test_a_skill_the_repository_wrote_is_not_overwritten(self) -> None:
        repo, agents = a_carrier(self.root)
        (repo / ".claude/skills/close").mkdir(parents=True)
        (repo / ".claude/skills/close/SKILL.md").write_text("---\nname: close\n---\n\nOurs.\n")

        with self.assertRaises(B.RefusedError):
            B.install_skills(repo, agents)
        self.assertIn("Ours.", (repo / ".claude/skills/close/SKILL.md").read_text())

        B.install_skills(repo, agents, force=True)
        self.assertNotIn("Ours.", (repo / ".claude/skills/close/SKILL.md").read_text())

    def test_an_unknown_skill_is_refused(self) -> None:
        repo, agents = a_carrier(self.root)

        with self.assertRaises(B.RefusedError):
            B.install_skills(repo, agents, ["nothing"])

    def test_check_finds_an_installed_skill_edited_by_hand_or_behind_its_base(self) -> None:
        repo, agents = a_carrier(self.root)
        B.install_skills(repo, agents)
        self.assertEqual(B.installed_skill_problems(repo, agents), [])

        installed = repo / ".claude/skills/close/SKILL.md"
        installed.write_text(installed.read_text() + "\nedited\n")
        self.assertEqual(len(B.installed_skill_problems(repo, agents)), 1)

        B.install_skills(repo, agents)
        (repo / ".claude/skills/close/LOCAL.md").write_text("## 9. Later\n\nAdded after the install.\n")
        self.assertEqual(len(B.installed_skill_problems(repo, agents)), 1)

    def test_check_ignores_skills_the_repository_wrote(self) -> None:
        repo, agents = a_carrier(self.root)
        (repo / ".claude/skills/mine").mkdir(parents=True)
        (repo / ".claude/skills/mine/SKILL.md").write_text("---\nname: mine\n---\n\nOurs.\n")

        self.assertEqual(B.installed_skill_problems(repo, agents), [])

    def test_an_installed_skill_whose_base_is_gone_is_a_problem(self) -> None:
        repo, agents = a_carrier(self.root)
        B.install_skills(repo, agents)
        (agents / "method/skills/close/SKILL.md").unlink()

        self.assertEqual(len(B.installed_skill_problems(repo, agents)), 1)

    def test_verify_fails_on_a_stale_installed_skill(self) -> None:
        repo, agents = a_carrier(self.root)
        B.install_skills(repo, agents)
        self.assertEqual(B.verify_problems(agents), [])

        installed = repo / ".claude/skills/close/SKILL.md"
        installed.write_text(installed.read_text() + "\nedited\n")
        self.assertTrue(any("install-skills" in p for p in B.verify_problems(agents)))

    def test_the_command_installs_and_checks(self) -> None:
        repo, agents = a_carrier(self.root)

        code, out = run("install-skills", "--repo", str(repo), "--bundle", str(agents))
        self.assertEqual(code, 0, out)
        code, out = run("install-skills", "--check", "--repo", str(repo), "--bundle", str(agents))
        self.assertEqual(code, 0, out)

        (repo / ".claude/skills/close/LOCAL.md").write_text("## 9. Later\n\nMore.\n")
        code, out = run("install-skills", "--check", "--repo", str(repo), "--bundle", str(agents))
        self.assertEqual(code, 1, out)


LOG = """# Session changelog

Newest entry below the line.

---

## 2026-01-02 · s-abcdef-111111 — An earlier session

**What.** Something.

---

## Entry format

```
## YYYY-MM-DD · s-<repo6>-<content6> — <one-line title>   (id: `bundle.py id s "<title>"`)
**What.** What changed, concretely.
**Why.** The reason, including the request
that prompted it.
```
"""


class NewEntry(Base):
    def test_the_log_s_own_format_is_the_template(self) -> None:
        log = self.root / "log.md"
        log.write_text(LOG)

        entry = B.new_entry("A new session", "r-abcdef", "2026-01-03", B.entry_template(log))

        self.assertTrue(entry.startswith("## 2026-01-03 · " + B.record_id("s", "A new session", "r-abcdef") + " — A new session\n"))
        self.assertIn("**What.** <!-- What changed, concretely. -->", entry)
        self.assertIn("**Why.** <!-- The reason, including the request that prompted it. -->", entry)
        self.assertNotIn("(id:", entry)

    def test_without_a_format_in_the_log_the_method_s_template_is_used(self) -> None:
        log = self.root / "log.md"
        log.write_text("# Log\n")
        agents = make_bundle(self.root)
        (agents / "method/prompt-context.md").write_text(
            "# Context\n\n### 5. `.claude/logs/agent-changelog.md`\n\n```markdown\n## YYYY-MM-DD · s-x — <t>\n"
            "**What.** What changed.\n**Learned.** General and local.\n```\n")

        entry = B.new_entry("T", "r-abcdef", "2026-01-03", B.entry_template(log, agents))

        self.assertIn("**Learned.** <!-- General and local. -->", entry)

    def test_fields_a_newer_method_added_reach_a_log_with_its_own_format_and_are_named(self) -> None:
        repo, agents = a_carrier(self.root)
        (agents / "method/prompt-context.md").write_text(
            "# Context\n\n### 5. `.claude/logs/agent-changelog.md`\n\n```markdown\n## YYYY-MM-DD · s-x — <t>\n"
            "**What.** What changed.\n**Why.** The reason.\n**Not verified.** What could not be checked.\n**Learned** General and local.\n```\n")
        log = repo / ".claude/logs/agent-changelog.md"
        log.parent.mkdir(parents=True)
        log.write_text(LOG)

        entry = B.new_entry("T", "r-abcdef", "2026-01-03", B.entry_template(log, agents))

        self.assertIn("**What.** <!-- What changed, concretely. -->", entry)
        self.assertEqual(entry.count("**Why.**"), 1)
        self.assertIn("**Not verified.** <!-- from the method's entry format, which this log's lacks: What could not be checked. -->", entry)
        self.assertLess(entry.index("**Why.**"), entry.index("**Not verified.**"))
        self.assertIn("**Learned** <!-- from the method's", entry)

        code, out = run("new", "entry", "T", "--log", str(log), "--repo", str(repo), "--bundle", str(agents))

        self.assertEqual(code, 0, out)
        said = [line for line in out.split("\n") if "lacks" in line and "<!--" not in line]
        self.assertEqual(len(said), 1, out)
        self.assertIn("**Not verified.** **Learned**;", said[0])

    def test_the_entry_is_inserted_above_the_newest_one(self) -> None:
        entry = B.new_entry("A new session", "r-abcdef", "2026-01-03", B.entry_template_text(LOG))

        text = B.insert_entry(LOG, entry)

        self.assertLess(text.index("A new session"), text.index("An earlier session"))
        self.assertGreater(text.index("A new session"), text.index("Newest entry below the line"))
        self.assertEqual(text.count("```"), 2)

    def test_a_log_with_no_entry_yet_takes_it_above_its_format(self) -> None:
        first = LOG.split("## 2026-01-02")[0] + "## Entry format" + LOG.split("## Entry format")[1]

        text = B.insert_entry(first, "## 2026-01-03 · s-abcdef-222222 — First\n")

        self.assertLess(text.index("— First"), text.index("## Entry format"))

    def test_the_command_writes_into_the_log(self) -> None:
        repo, agents = a_carrier(self.root)
        log = repo / ".claude/logs/agent-changelog.md"
        log.parent.mkdir(parents=True)
        log.write_text(LOG)

        code, out = run("new", "entry", "A", "new", "session", "--log", str(log), "--repo", str(repo), "--write")

        self.assertEqual(code, 0, out)
        self.assertIn("— A new session", log.read_text())


class Count(Base):
    def test_one_entry_counts_once_however_often_it_names_the_symptom(self) -> None:
        log = self.root / "log.md"
        log.write_text(LOG + "\n## 2026-01-04 · s-abcdef-333333 — Later\n\nThe stash was refused.\nThe stash again.\n")
        (self.root / "ledger.md").write_text("Task 1: Ruling: stash refused\nTask 2: fine\n")

        hits = B.count_mentions("STASH", [log, self.root / "ledger.md"])

        self.assertEqual(len(hits), 2)
        self.assertEqual(hits[0].where, "2026-01-04 · s-abcdef-333333 — Later")
        self.assertEqual(hits[1].where, "line 1")

    def test_the_command_prints_the_count(self) -> None:
        log = self.root / "log.md"
        log.write_text(LOG)

        code, out = run("count", "earlier", str(log))

        self.assertEqual(code, 0, out)
        self.assertIn("1 entries", out)


class MemoryDiff(Base):
    def test_each_memory_says_whether_the_repository_holds_what_it_names(self) -> None:
        repo = init_repo(self.root / "repo")
        (repo / "notes.md").write_text("Start the emulator with `-gpu swiftshader`.\n")
        commit(repo)
        memory = self.root / "memory"
        memory.mkdir()
        (memory / "MEMORY.md").write_text("- index\n")
        (memory / "gpu.md").write_text('---\nname: "gpu"\ndescription: "the software GPU"\n---\n\nUse `-gpu swiftshader`.\n')
        (memory / "lone.md").write_text('---\nname: "lone"\ndescription: "only here"\n---\n\nRun `make wobble`.\n')
        (memory / "prose.md").write_text('---\nname: "prose"\ndescription: "no code span"\n---\n\nKeep one scale.\n')
        (repo / ".agents").mkdir()
        (repo / ".agents/README.md").write_text("The bundle says `make wobble` too.\n")
        commit(repo)

        found = {m.name: m for m in B.memory_report(memory, repo)}

        self.assertEqual(sorted(found), ["gpu", "lone", "prose"])
        self.assertEqual(found["gpu"].found_in, ["notes.md"])
        self.assertEqual(found["lone"].found_in, [])
        self.assertTrue(found["lone"].searched)
        self.assertFalse(found["prose"].searched)

    def test_a_memory_with_nested_frontmatter_is_read(self) -> None:
        repo = init_repo(self.root / "repo")
        commit(repo)
        memory = self.root / "memory"
        memory.mkdir()
        (memory / "nested.md").write_text("---\nname: nested\ndescription: with metadata\nmetadata:\n  type: feedback\n---\n\nBody.\n")

        found = B.memory_report(memory, repo)

        self.assertEqual([(m.name, m.description) for m in found], [("nested", "with metadata")])

    def test_the_memory_folder_is_named_after_the_repository_path(self) -> None:
        self.assertEqual(B.memory_dir(Path("/a/b.c/d_e"), Path("/h")), Path("/h/.claude/projects/-a-b-c-d-e/memory"))


class TriggerEval(Base):
    """The trigger eval reads a session's stream and stops at its first tool call."""

    def setUp(self) -> None:
        super().setUp()
        from meta.tests.support import ROOT, _load
        self.T = _load("trigger", ROOT / "evals/skills/trigger.py")

    def test_the_first_tool_call_decides(self) -> None:
        skill = '{"type":"assistant","message":{"content":[{"type":"tool_use","name":"Skill","input":{"skill":"close"}}]}}'
        other = '{"type":"assistant","message":{"content":[{"type":"tool_use","name":"Read","input":{}}]}}'
        text = '{"type":"assistant","message":{"content":[{"type":"text","text":"hi"}]}}'

        self.assertEqual(self.T.first_call([text, skill, other]), ("Skill", "close"))
        self.assertEqual(self.T.first_call([text, other, skill]), ("Read", ""))
        self.assertEqual(self.T.first_call([text, "not json"]), (None, ""))

    def test_rates_are_judged_against_their_thresholds(self) -> None:
        results = [{"expect": True, "fired": True}] * 8 + [{"expect": True, "fired": False}] * 2 \
            + [{"expect": False, "fired": False}] * 9 + [{"expect": False, "fired": True}]

        verdict = self.T.verdict(results)

        self.assertEqual((verdict["fire"], verdict["misfire"]), (0.8, 0.1))
        self.assertTrue(verdict["passed"])
        self.assertFalse(self.T.verdict(results + [{"expect": False, "fired": True}])["passed"])
