"""bundle.py surfaces: Cursor's and Copilot's files generated from the ones Claude Code reads, and checked.

The one source is what Claude Code reads (`.claude/rules/`, `.claude/agents/`) and `AGENTS.md`; the other
assistants' copies are generated, marked, and fail `verify` when stale or edited (2026-10-08).
"""

from __future__ import annotations

import contextlib
import io
from pathlib import Path

from meta.tests.support import Base, bundle, init_repo, make_bundle

B = bundle

RULE = '---\npaths:\n  - "src/database/**"\n  - "src/models/**"\n---\n# Database access\n\nQueries go through the repository layer.\n'
ALWAYS = "# Everywhere\n\nNo rule here names a path.\n"
REVIEWER = ('---\nname: "knowledge-reviewer"\ndescription: "Reviews a diff against the knowledge."\n'
            'tools: "Read, Grep, Glob, Bash"\nexperimental: {cacheTtl: "5m"}\n---\n\nYou review one change.\n')
WRITER = '---\nname: "fixer"\ndescription: "Fixes one thing."\ntools: "Read, Edit, Write, WebFetch"\n---\n\nYou fix it.\n'


def run(*argv: str) -> tuple[int, str]:
    out = io.StringIO()
    with contextlib.redirect_stdout(out):
        code = B.main(list(argv))
    return code, out.getvalue()


class Surfaces(Base):
    def a_repo(self, kinds: list[str] | None = None) -> Path:
        repo = init_repo(self.root / "repo")
        agents = make_bundle(repo)
        if kinds is not None:
            B.write_carrier(agents, {**(B.read_carrier(agents) or {}), "surfaces": kinds})
        (repo / "AGENTS.md").write_text("# AGENTS.md\n")
        (repo / ".claude/rules").mkdir(parents=True)
        (repo / ".claude/rules/database.md").write_text(RULE)
        (repo / ".claude/agents").mkdir(parents=True)
        (repo / ".claude/agents/knowledge-reviewer.md").write_text(REVIEWER)
        return repo

    def test_a_rule_with_paths_becomes_a_cursor_rule_and_a_copilot_instruction(self) -> None:
        repo = self.a_repo()
        B.write_surfaces(repo, ["cursor", "copilot"])

        mdc = (repo / ".cursor/rules/database.mdc").read_text()
        self.assertTrue(mdc.startswith("---\n# Generated by bundle.py surfaces from .claude/rules/database.md;"), mdc)
        self.assertIn("\nglobs: src/database/**, src/models/**\n", mdc)
        self.assertIn("\nalwaysApply: false\n", mdc)
        self.assertIn('\ndescription: "Database access"\n', mdc)
        self.assertTrue(mdc.endswith("# Database access\n\nQueries go through the repository layer.\n"), mdc)
        instructions = (repo / ".github/instructions/database.instructions.md").read_text()
        self.assertIn('\napplyTo: "src/database/**, src/models/**"\n', instructions)
        self.assertIn("Queries go through the repository layer.", instructions)

    def test_a_rule_without_paths_applies_always(self) -> None:
        repo = self.a_repo()
        (repo / ".claude/rules/everywhere.md").write_text(ALWAYS)
        B.write_surfaces(repo, ["cursor", "copilot"])

        self.assertIn("\nalwaysApply: true\n", (repo / ".cursor/rules/everywhere.mdc").read_text())
        self.assertIn('\napplyTo: "**"\n', (repo / ".github/instructions/everywhere.instructions.md").read_text())

    def test_a_stale_copy_fails_the_check_and_writing_again_mends_it(self) -> None:
        repo = self.a_repo()
        B.write_surfaces(repo, ["cursor"])
        self.assertEqual(B.surface_problems(repo, ["cursor"]), [])

        (repo / ".claude/rules/database.md").write_text(RULE.replace("repository layer", "query module"))
        problems = B.surface_problems(repo, ["cursor"])
        self.assertEqual(len(problems), 1, problems)
        self.assertIn(".cursor/rules/database.mdc", problems[0])

        B.write_surfaces(repo, ["cursor"])
        self.assertEqual(B.surface_problems(repo, ["cursor"]), [])

    def test_a_hand_edit_to_a_generated_copy_fails_the_check(self) -> None:
        repo = self.a_repo()
        B.write_surfaces(repo, ["copilot"])
        path = repo / ".github/instructions/database.instructions.md"
        path.write_text(path.read_text() + "\nOne more rule, written here.\n")

        self.assertIn(".github/instructions/database.instructions.md", " ".join(B.surface_problems(repo, ["copilot"])))

    def test_a_hand_written_file_is_never_overwritten_without_force(self) -> None:
        repo = self.a_repo()
        (repo / ".cursor/rules").mkdir(parents=True)
        (repo / ".cursor/rules/database.mdc").write_text("---\ndescription: mine\n---\nMine.\n")

        with self.assertRaises(B.RefusedError):
            B.write_surfaces(repo, ["cursor"])
        self.assertEqual((repo / ".cursor/rules/database.mdc").read_text(), "---\ndescription: mine\n---\nMine.\n")
        self.assertIn(".cursor/rules/database.mdc", B.hand_written_surfaces(repo, ["cursor"]))

        B.write_surfaces(repo, ["cursor"], force=True)
        self.assertIn("Generated by bundle.py surfaces", (repo / ".cursor/rules/database.mdc").read_text())

    def test_a_copy_whose_source_is_gone_is_reported_and_removed(self) -> None:
        repo = self.a_repo()
        B.write_surfaces(repo, ["cursor"])
        (repo / ".claude/rules/database.md").unlink()

        self.assertIn("source", " ".join(B.surface_problems(repo, ["cursor"])))
        written, removed = B.write_surfaces(repo, ["cursor"])
        self.assertIn(".cursor/rules/database.mdc", removed)
        self.assertFalse((repo / ".cursor/rules/database.mdc").exists())

    def test_agents_are_read_only_in_cursor_and_keep_their_tools_in_copilot(self) -> None:
        repo = self.a_repo()
        (repo / ".claude/agents/fixer.md").write_text(WRITER)
        B.write_surfaces(repo, ["cursor", "copilot"])

        cursor = (repo / ".cursor/agents/knowledge-reviewer.md").read_text()
        self.assertIn("\nreadonly: true\n", cursor)
        self.assertIn("\nmodel: inherit\n", cursor)
        self.assertNotIn("cacheTtl", cursor)
        self.assertTrue(cursor.endswith("You review one change.\n"), cursor)
        self.assertIn("\nreadonly: false\n", (repo / ".cursor/agents/fixer.md").read_text())
        copilot = (repo / ".github/agents/knowledge-reviewer.agent.md").read_text()
        self.assertIn('\ntools: ["read", "search", "execute"]\n', copilot)
        self.assertIn('\ntools: ["read", "edit", "web"]\n', (repo / ".github/agents/fixer.agent.md").read_text())

    def test_the_copilot_pointer_is_written_only_where_none_was_written_by_hand(self) -> None:
        repo = self.a_repo()
        B.write_surfaces(repo, ["copilot"])
        pointer = (repo / ".github/copilot-instructions.md").read_text()
        self.assertIn("AGENTS.md", pointer)
        self.assertTrue(pointer.startswith("<!-- Generated by bundle.py surfaces from AGENTS.md;"), pointer)

        (repo / ".github/copilot-instructions.md").write_text("Our own words.\n")
        written, _ = B.write_surfaces(repo, ["copilot"])
        self.assertEqual((repo / ".github/copilot-instructions.md").read_text(), "Our own words.\n")
        self.assertNotIn(".github/copilot-instructions.md", written)
        self.assertEqual(B.surface_problems(repo, ["copilot"]), [])

    def test_verify_checks_the_surfaces_a_carrier_names_and_no_others(self) -> None:
        repo = self.a_repo()
        self.assertFalse([p for p in B.verify_problems(repo / ".agents") if "surfaces" in p or ".cursor" in p])

        B.write_carrier(repo / ".agents", {**B.read_carrier(repo / ".agents"), "surfaces": ["cursor", "vim"]})
        problems = B.verify_problems(repo / ".agents")
        self.assertIn(".cursor/rules/database.mdc", " ".join(problems))
        self.assertIn("`surfaces` names `vim`", " ".join(problems))

    def test_the_command_writes_what_the_carrier_names(self) -> None:
        repo = self.a_repo(["cursor"])

        code, out = run("surfaces", "--repo", str(repo))
        self.assertEqual(code, 1, out)
        code, out = run("surfaces", "--repo", str(repo), "--write")
        self.assertEqual(code, 0, out)
        self.assertIn("+ .cursor/rules/database.mdc", out)
        self.assertFalse((repo / ".github").exists())
        code, out = run("surfaces", "--repo", str(repo))
        self.assertEqual(code, 0, out)
