#!/usr/bin/env python3
"""The home repository's half of the agent-guides tools. Python 3.11+, standard library only.

The carrier tool (`.agents/tools/bundle.py`) is what every repository that carries the bundle runs.
This one is what only the home runs: it builds the shipped knowledge from the full notes in
`sources/`, cuts a release, and carries it to the other carriers. It loads the carrier tool rather
than copying from it, so every rule both need exists once.

    python3 meta/tools/release.py build [--check]         generated knowledge and SHA256SUMS, from sources/
    python3 meta/tools/release.py release X.Y.Z           version, date, build; prints the tag to create
    python3 meta/tools/release.py check                   the home's CI: verify, build --check, privacy, links
    python3 meta/tools/release.py gather [REPO...] --out DIR    phase 1: each carrier against its release tag
    python3 meta/tools/release.py intake DIR              the gathered outboxes into meta/tracking/
    python3 meta/tools/release.py lost BASE SNAPSHOT...   lines a carrier added that the home does not hold
    python3 meta/tools/release.py splice [REPO...] [--write --backup DIR]   phase 2: the release into each carrier
    python3 meta/tools/release.py register [REPO...]      the carriers table, by stored carrier id
    python3 meta/tools/release.py align [REPO...]         phase 3: every carrier on one version
    python3 meta/tools/release.py note-state SLUG STATE   move a full note between states, then build
    python3 meta/tools/release.py report [--check]        sizes, budgets and the knowledge funnel
    python3 meta/tools/release.py triage [--apply-discards]    candidates due for discard

The tests are in `meta/tests/` (`python3 -m unittest discover -s meta/tests -t .`).
"""

from __future__ import annotations

import argparse
import datetime
import importlib.util
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

if sys.version_info < (3, 11):
    sys.exit(f"release.py needs Python 3.11 or newer (this is {sys.version.split()[0]})")

ROOT = Path(__file__).resolve().parents[2]


def _load_bundle():  # noqa: ANN202 -- a module
    if "bundle" in sys.modules:
        return sys.modules["bundle"]
    spec = importlib.util.spec_from_file_location("bundle", ROOT / ".agents/tools/bundle.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["bundle"] = module
    spec.loader.exec_module(module)
    return module


B = _load_bundle()
RefusedError = B.RefusedError


# --- the build: sources/ -> .agents/knowledge/ -------------------------------------------------------
# A note is written once, in full, in `sources/notes/<state>/<slug>.md`. Everything a carrier reads about
# it is derived from that file by code: the short note it ships, its row in every index table, and its
# card (claim, where it stops applying, the check). Nothing derived is written by hand, so nothing
# derived can disagree with its source; `build --check` fails when the output is not what the sources
# produce.

NOTE_STATES = ("active", "review", "retired")
SHIPPED_STATES = ("active", "review")
# The sections of a full note that stay home: where a note came from, what it rests on, what was
# measured. A carrier reads the mechanism, the boundary and the cost; the evidence is for the release.
EVIDENCE_SECTIONS = ("Where it came from", "Literature", "Evidence")
BOUNDARY_SECTION = "When it does NOT apply"
# The phases of work, in the order `INDEX.md` lists them. A note's `phases` field names them by key.
PHASES = ("plan", "dataset", "implement", "tests", "review", "verify", "debug")
CONFIDENCE = ("measured", "reasoned", "inherited")
REQUIRED = ("slug", "topic", "claim", "confidence", "check")
SHIPPED_FIELDS = ("slug", "topic", "claim", "confidence", "check", "boundary")
BANNER = "<!-- Generated by the release build from the full notes. Edit the source, never this file. -->\n"
NOTE_BANNER = "generated from the full note by the release build; edit the source, never this file"
GENERATED_MARKER = re.compile(r"^<!-- generated: (cards|about|founded) ?([\w-]*) -->$", re.MULTILINE)
PHASE_TOKEN = re.compile(r"\{\{notes:([\w-]+)\}\}")
REVIEW_MARK = " ⚠ review"


@dataclass
class Note:
    slug: str
    state: str
    meta: dict
    body: str
    where: str
    boundary: str = ""

    @property
    def topic(self) -> str:
        return self.meta["topic"]


class BuildError(RuntimeError):
    """The sources do not describe a buildable knowledge base; every problem is listed."""


def _headings(body: str) -> list[tuple[int, int, str]]:
    """(line index, level, text) of every heading outside fenced blocks."""
    lines = body.split("\n")
    prose = B._prose(lines)
    out = []
    for i, line in enumerate(lines):
        m = B.HEADING.match(line) if prose[i] else None
        if m:
            out.append((i, len(m.group(1)), m.group(2)))
    return out


def short_body(body: str) -> str:
    """The body a carrier ships: everything before the first evidence section."""
    lines = body.split("\n")
    cut = next((i for i, level, text in _headings(body) if level == 2 and text in EVIDENCE_SECTIONS), len(lines))
    return "\n".join(lines[:cut]).rstrip("\n") + "\n"


def _section_lines(body: str, heading: str) -> list[str] | None:
    lines = body.split("\n")
    heads = _headings(body)
    for n, (i, level, text) in enumerate(heads):
        if level == 2 and text == heading:
            end = next((j for j, lv, _ in heads[n + 1 :] if lv <= 2), len(lines))
            return lines[i + 1 : end]
    return None


BOLD_LEAD = re.compile(r"^- \*\*(.+?)\*\*")


def lead_ins(body: str) -> list[str] | None:
    """The bold lead-ins of *When it does NOT apply*, or None when any top-level bullet has none.

    A section written as bullets that each open in bold states its cases in their own words; the card
    lists those words. A section in prose, or with one bullet that does not open in bold, has no such
    words, and its note carries a `boundary:` written for the card instead.
    """
    section = _section_lines(body, BOUNDARY_SECTION)
    if section is None:
        return None
    bullets = [line for line in section if line.startswith("- ")]
    if not bullets or any(not BOLD_LEAD.match(line) for line in bullets):
        return None
    return [BOLD_LEAD.match(line).group(1).strip().rstrip(".:;,").strip() for line in bullets]


def load_notes(sources: Path, strict_cards: bool = True) -> list[Note]:
    """Every full note under `sources/notes/<state>/`, parsed and checked; all problems at once.

    With `strict_cards` off, a note whose card has no boundary yet is loaded anyway (the migration proof
    renders the old tables, which had no card column).
    """
    notes, problems = [], []
    for state in NOTE_STATES:
        for path in sorted((sources / "notes" / state).glob("*.md"), key=lambda p: p.name.encode()):
            where = path.relative_to(sources.parent).as_posix()
            try:
                meta, body = B.read_frontmatter(path.read_text(encoding="utf-8"), where)
            except B.FrontmatterError as error:
                problems.append(str(error))
                continue
            note = Note(path.stem, state, meta, body, where)
            problems += [p for p in _note_problems(note) if strict_cards or "boundary" not in p]
            notes.append(note)
    slugs = [n.slug for n in notes]
    problems += [f"note {s!r} is in more than one state folder" for s in sorted({s for s in slugs if slugs.count(s) > 1})]
    if problems:
        raise BuildError("\n".join(problems))
    return notes


def _note_problems(note: Note) -> list[str]:
    meta, problems = note.meta, []
    missing = [k for k in REQUIRED if not meta.get(k)]
    if note.state == "retired":
        missing = [k for k in ("slug", "claim") if not meta.get(k)]
    problems += [f"{note.where}: missing `{k}`" for k in missing]
    if meta.get("slug") and meta["slug"] != note.slug:
        problems.append(f"{note.where}: `slug: {meta['slug']}` is not the file name")
    if meta.get("confidence") and meta["confidence"] not in CONFIDENCE:
        problems.append(f"{note.where}: `confidence` is one of {', '.join(CONFIDENCE)}")
    unknown = [p for p in meta.get("phases") or [] if p not in PHASES]
    problems += [f"{note.where}: unknown phase {p!r} (one of {', '.join(PHASES)})" for p in unknown]
    for row in meta.get("about") or []:
        if not isinstance(row, dict) or set(row) != {"do", "wrong_when"}:
            problems.append(f"{note.where}: every `about` row is {{do, wrong_when}}")
    if note.state in SHIPPED_STATES:
        if not meta.get("phases"):
            problems.append(f"{note.where}: in no phase, so the index never routes to it")
        if not meta.get("about"):
            problems.append(f"{note.where}: in no *about to do* row")
        leads = lead_ins(note.body)
        if leads and meta.get("boundary"):
            problems.append(f"{note.where}: has both bold lead-ins under *{BOUNDARY_SECTION}* and a `boundary:`; keep one")
        elif leads:
            note.boundary = " · ".join(leads)
        elif meta.get("boundary"):
            note.boundary = meta["boundary"]
        else:
            problems.append(f"{note.where}: *{BOUNDARY_SECTION}* has no bold lead-in on every bullet, so the card "
                            "needs a `boundary:`")
    return problems


def _cell(text: str) -> str:
    return " ".join(str(text).split("\n")).replace("|", "\\|")


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(_cell(c) for c in cells) + " |"


def _link(note: Note, prefix: str) -> str:
    return f"[{note.slug}]({prefix}notes/{note.state}/{note.slug}.md)" + (REVIEW_MARK if note.state == "review" else "")


def _rests_on(meta: dict) -> str:
    return f"{meta['rests_on']} — **{meta['strength']}**" if meta.get("strength") else meta.get("rests_on", "")


@dataclass
class Order:
    """A row order other than the canonical one: used once, to reproduce the hand-ordered tables."""

    cards: dict[str, list[str]] = field(default_factory=dict)
    about: dict[str, list[tuple[str, int]]] = field(default_factory=dict)
    founded: dict[str, list[str]] = field(default_factory=dict)
    phases: dict[str, list[str]] = field(default_factory=dict)


def _ordered(items: list, key, override: list | None):  # noqa: ANN001, ANN202
    if override is None:
        return sorted(items, key=key)
    position = {k: i for i, k in enumerate(override)}
    unknown = [it for it in items if key(it) not in position]
    if unknown:
        raise BuildError(f"the given order lacks {sorted(map(str, map(key, unknown)))}")
    return sorted(items, key=lambda it: position[key(it)])


def render_area(template: str, area: str, notes: list[Note], topics: list[str], order: Order | None = None,
                cards: bool = True) -> str:
    """An area index from its template: every `<!-- generated: … -->` marker replaced by its table."""
    order = order or Order()
    shipped = [n for n in notes if n.state in SHIPPED_STATES]
    rank = {t: i for i, t in enumerate(topics)}
    here = [n for n in shipped if n.topic in rank]

    def table(kind: str, topic: str) -> str:
        if kind == "cards":
            rows = _ordered([n for n in here if n.topic == topic], lambda n: n.slug, order.cards.get(topic))
            head = ["Note", "Claim", "Not when", "Verify by"] if cards else ["Note", "Claim", "Verify by"]
            body = [_row([_link(n, "../"), n.meta["claim"], *([n.boundary] if cards else []), n.meta["check"]]) for n in rows]
        elif kind == "about":
            items = [(n, i, r) for n in here for i, r in enumerate(n.meta.get("about") or [])]
            items = _ordered(items, lambda it: (it[0].slug, it[1]), order.about.get(area)) if order.about.get(area) \
                else sorted(items, key=lambda it: (rank[it[0].topic], it[0].slug, it[1]))
            head = ["…do this", "Read", "Because the default answer is wrong when"]
            body = [_row([r["do"], _link(n, "../"), r["wrong_when"]]) for n, _, r in items]
        else:
            rows = _ordered(here, lambda n: n.slug, order.founded.get(area)) if order.founded.get(area) \
                else sorted(here, key=lambda n: (rank[n.topic], n.slug))
            head = ["Note", "Claim rests on", "Our evidence"]
            body = [_row([n.slug, _rests_on(n.meta), n.meta.get("our_evidence", "")]) for n in rows]
        return "\n".join([_row(head), "|" + "---|" * len(head), *body])

    return GENERATED_MARKER.sub(lambda m: table(m.group(1), m.group(2)), template)


def render_index(template: str, notes: list[Note], topics: list[str], order: Order | None = None) -> str:
    """`INDEX.md` from its template: every `{{notes:PHASE}}` replaced by that phase's notes."""
    order = order or Order()
    rank = {t: i for i, t in enumerate(topics)}
    shipped = [n for n in notes if n.state in SHIPPED_STATES]

    def cell(m: re.Match) -> str:
        phase = m.group(1)
        if phase not in PHASES:
            raise BuildError(f"INDEX template: unknown phase {phase!r}")
        members = [n for n in shipped if phase in n.meta.get("phases", [])]
        members = _ordered(members, lambda n: n.slug, order.phases.get(phase)) if order.phases.get(phase) \
            else sorted(members, key=lambda n: (rank.get(n.topic, len(rank)), n.slug))
        return " · ".join(_link(n, "") for n in members)

    return PHASE_TOKEN.sub(cell, template)


def short_note(note: Note) -> str:
    """The note a carrier ships: the card fields, and the body up to the evidence."""
    meta = {k: (note.boundary if k == "boundary" else note.meta.get(k)) for k in SHIPPED_FIELDS}
    return B.dump_frontmatter(meta, NOTE_BANNER) + short_body(note.body)


def area_topics(template: str) -> list[str]:
    return [m.group(2) for m in GENERATED_MARKER.finditer(template) if m.group(1) == "cards"]


def render_open(meta_dir: Path) -> str:
    """`knowledge/OPEN.md`: what a harvest checks before it offers something, from the home's records."""
    experiments = read_table(meta_dir / "tracking/experiments.md", "| Note | Experiment | Cost | Would change |")
    candidates = read_table(meta_dir / "tracking/candidates.md", "| Candidate | Kind | Lacks |", prefix=True)
    lines = [
        "# Open — what the home is still waiting for",
        "",
        "Generated at each release from the home repository's records. A harvest reads it before offering "
        "anything: an experiment queued here is one this repository may be able to run, and a candidate "
        "listed here should be extended with a new occurrence rather than offered again.",
        "",
        "## Experiments waiting to be run",
        "",
        "| Note | Experiment | Cost | Would change |",
        "|---|---|---|---|",
        *[_row(r[:4]) for r in experiments],
        "",
        "## Candidates waiting for what they lack",
        "",
        "| Candidate | Kind | Lacks |",
        "|---|---|---|",
        *[_row(r[:3]) for r in candidates],
    ]
    return "\n".join(lines) + "\n"


def split_row(line: str) -> list[str]:
    """The cells of one markdown table row; `\\|` is a pipe inside a cell."""
    cells, current, i, inner = [], [], 0, line.strip()[1:]
    inner = inner[:-1] if inner.endswith("|") and not inner.endswith("\\|") else inner
    while i < len(inner):
        if inner[i] == "\\" and inner[i + 1 : i + 2] == "|":
            current.append("|")
            i += 2
            continue
        if inner[i] == "|":
            cells.append("".join(current).strip())
            current = []
        else:
            current.append(inner[i])
        i += 1
    cells.append("".join(current).strip())
    return cells


def read_table(path: Path, header: str, prefix: bool = False) -> list[list[str]]:
    """The rows of the first table in `path` whose header row is (or, with `prefix`, starts with) `header`."""
    if not path.is_file():
        return []
    lines = path.read_text(encoding="utf-8").split("\n")
    for i, line in enumerate(lines):
        if line == header or (prefix and line.startswith(header)):
            rows = []
            for row in lines[i + 2 :]:
                if not row.startswith("|"):
                    break
                rows.append(split_row(row))
            return rows
    return []


def build_outputs(root: Path, order: Order | None = None, cards: bool = True, banner: bool = True) -> dict[str, str]:
    """Everything the build writes into `.agents/`, as {bundle-relative path: content}, SHA256SUMS aside."""
    sources = root / "sources"
    notes = load_notes(sources)
    templates = sources / "templates"
    areas = sorted((templates / "areas").glob("*.md"), key=lambda p: p.name.encode())
    topics_by_area = {p.stem: area_topics(p.read_text(encoding="utf-8")) for p in areas}
    topics = [t for ts in topics_by_area.values() for t in ts]
    problems = [f"{t}: a topic in more than one area template" for t in sorted({t for t in topics if topics.count(t) > 1})]
    problems += [f"{n.where}: topic {n.topic!r} has no `<!-- generated: cards {n.topic} -->` in any area template"
                 for n in notes if n.state in SHIPPED_STATES and n.topic not in topics]
    if problems:
        raise BuildError("\n".join(problems))
    head = BANNER if banner else ""
    out = {f"knowledge/notes/{n.state}/{n.slug}.md": short_note(n) for n in notes if n.state in SHIPPED_STATES}
    for path in areas:
        out[f"knowledge/areas/{path.name}"] = head + render_area(
            path.read_text(encoding="utf-8"), path.stem, notes, topics_by_area[path.stem], order, cards)
    out["knowledge/INDEX.md"] = head + render_index((templates / "INDEX.md").read_text(encoding="utf-8"), notes, topics, order)
    out["knowledge/OPEN.md"] = head + render_open(root / "meta")
    return out


GENERATED = ("knowledge/notes/", "knowledge/areas/", "knowledge/INDEX.md", "knowledge/OPEN.md")


def _generated_on_disk(bundle: Path) -> set[str]:
    return {rel for rel in B.shipped(bundle) if rel.startswith(GENERATED)}


def build(root: Path = ROOT, check: bool = False) -> list[str]:
    """Writes, or with `check` compares, everything generated and then `SHA256SUMS`.

    Returns:
        With `check`: one problem per generated file that is stale, missing or not produced by the sources,
        and a stale `SHA256SUMS`. Without: what was written or removed.
    """
    bundle = root / ".agents"
    outputs = build_outputs(root)
    stale = sorted(_generated_on_disk(bundle) - set(outputs), key=str.encode)
    if check:
        problems = [f"{rel}: generated, and not what the sources produce (run `release.py build`)"
                    for rel, text in sorted(outputs.items()) if not (bundle / rel).is_file()
                    or (bundle / rel).read_text(encoding="utf-8") != text]
        problems += [f"{rel}: generated by nothing in sources/; `release.py build` removes it" for rel in stale]
        if not problems and (not (bundle / B.CHECKSUMS).is_file()
                             or (bundle / B.CHECKSUMS).read_text(encoding="utf-8") != B.checksums_text(bundle)):
            problems.append(f"{B.CHECKSUMS}: not the checksums of the bundle as it is (run `release.py build`)")
        return problems
    changes = []
    for rel, text in outputs.items():
        path = bundle / rel
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            changes.append(f"wrote {rel}")
    for rel in stale:
        (bundle / rel).unlink()
        changes.append(f"removed {rel}")
    B.write_checksums(bundle)
    return changes


# --- versions, tags and the release ------------------------------------------------------------------


def git(*args: str, repo: Path = ROOT, binary: bool = False) -> str | bytes:
    return B.git(repo, *args, binary=binary)


def tags(repo: Path = ROOT) -> list[str]:
    """The release tags, `vX.Y.Z`, oldest first by Semantic Versioning precedence."""
    names = [n for n in str(git("tag", "-l", "v*", repo=repo)).split() if B.SEMVER.match(n[1:])]
    return sorted(names, key=B.semver_key)


def tag_dates(repo: Path = ROOT) -> dict[str, str]:
    """{tag: date of the commit it tags}: a retro-tag counts from its commit, not from the day it was made."""
    out = str(git("for-each-ref", "refs/tags/v*", "--format=%(refname:short) %(*committerdate:short)%(committerdate:short)", repo=repo))
    dates = {}
    for line in out.splitlines():
        name, _, date = line.partition(" ")
        dates[name] = date[:10]
    return dates


def legacy_version(tree: Path) -> str | None:
    """The version a pre-0.0.22 bundle declares, as SemVer: its integer `version: N` becomes 0.0.N."""
    value = B.field(B.header(tree / "README.md"), "version") if (tree / "README.md").is_file() else None
    return f"0.0.{int(value)}" if value and value.isdigit() else None


def installed_version(tree: Path) -> str | None:
    return B.bundle_version(tree) or legacy_version(tree)


def set_version(root: Path, version: str, released: str) -> None:
    readme = root / ".agents/README.md"
    data, body = B.read_frontmatter(readme.read_text(encoding="utf-8"), str(readme))
    data.update({"version": version, "released": released})
    readme.write_text(B.dump_frontmatter(data) + body, encoding="utf-8")


def release(version: str, root: Path = ROOT) -> str:
    """Cuts a release: version and date into the README, the build, and the tag command to run.

    Refused unless the version is newer than every release tag and the changelog has its dated section:
    a release nobody described is a release nobody can triage.
    """
    B.semver_key(version)
    existing = tags(root)
    if existing and B.semver_key(version) <= B.semver_key(existing[-1][1:]):
        raise RefusedError(f"{version} is not newer than the last release, {existing[-1]}")
    text = (root / ".agents" / B.CHANGELOG).read_text(encoding="utf-8")
    section = next((m for m in B.CHANGELOG_SECTION.finditer(text) if m.group(1) == version), None)
    if section is None or not section.group(2):
        raise RefusedError(f"{B.CHANGELOG} has no `## [{version}] - YYYY-MM-DD` section; describe the release first")
    set_version(root, version, section.group(2))
    build(root)
    return f'git tag -a v{version} -m "agent-guides {version}"'


# --- the home's own checks -----------------------------------------------------------------------------
# The sessions only the home runs: their `Reads:` lists name paths from the repository root.
HOME_SESSIONS = {"sync": ("meta/method/prompt-sync.md", 0), "merge": ("meta/method/prompt-merge.md", 0)}


def home_files(root: Path = ROOT) -> list[Path]:
    return [p for folder in ("meta", "sources") for p in sorted((root / folder).rglob("*"))
            if p.is_file() and "__pycache__" not in p.parts and not any(part.startswith(".") for part in p.relative_to(root).parts)]


def home_link_problems(root: Path = ROOT) -> list[str]:
    """Dead links in `meta/` and `sources/`, and links into the generated notes, which move with a note's state."""
    problems = []
    for path in home_files(root):
        if path.suffix != ".md":
            continue
        rel = path.relative_to(root).as_posix()
        for target, resolved in B._links(root, rel):
            if not (root / resolved).exists():
                problems.append(f"{rel}: links to {target}, which does not exist")
            elif resolved.startswith(".agents/knowledge/notes/"):
                problems.append(f"{rel}: links to the generated {target}; link the full note in sources/notes/")
    return problems


def home_session_problems(root: Path = ROOT) -> list[str]:
    problems = []
    for name, (rel, index) in HOME_SESSIONS.items():
        path = root / rel
        found = B.reads_lists(path.read_text(encoding="utf-8")) if path.is_file() else []
        if index >= len(found):
            problems.append(f"session {name!r}: {rel} has no `Reads:` list number {index}")
            continue
        problems += [f"session {name!r}: {p}" for p in B._session_parts(root, found[index])[1]]
    return problems


def check(root: Path = ROOT) -> tuple[list[str], list[str]]:
    """The home's CI: the bundle verifies, the build is current, the records link and leak nothing.

    Returns:
        (problems, notes): every failure, and the privacy warnings and allowances to print.
    """
    bundle = root / ".agents"
    privacy = B.privacy_check(bundle)
    problems = B.verify_problems(bundle, privacy) + build(root, check=True)
    home = B.privacy_check(paths=home_files(root))
    problems += [f"privacy: {f.where} {f.rule}: {f.match}" for f in home.failures]
    problems += B.invisible_characters(root, [p.relative_to(root).as_posix() for p in home_files(root)])
    problems += home_link_problems(root) + home_session_problems(root) + B.budget_problems(bundle)
    return problems, privacy.notes() + home.notes()


# --- carriers: gather, intake, lost, splice, register, align ------------------------------------------
# A carrier writes only what it owns: its carrier file and its harvest outbox. So a meta-session over
# carriers on the current layout gathers their outboxes and checks, by their checksums, that nothing
# else moved. A carrier still on a layout from before 0.0.22 is compared line by line with the release
# it holds, which the home has under its tag, and `lost` names every line it added.

GATHER_MARKER = ".bundle-gather"
CANDIDATES_HEADER = "| Candidate | Kind | Lacks | Evidence | First seen |"
EXPERIMENTS_RUN_HEADER = "| Date | Note | Where | What was run | Result | Verdict |"


def _names(repos: list[Path]) -> list[str]:
    if not repos:
        raise RefusedError("no repositories in scope: name the carriers this session has open")
    names = [repo.name for repo in repos]
    twice = sorted({n for n in names if names.count(n) > 1})
    if twice:
        raise RefusedError(f"two carriers are both called {', '.join(twice)}: give each checkout its own folder name")
    return names


def extract(tag: str, into: Path, root: Path = ROOT) -> Path:
    """The `.agents` folder of a release tag, from `git archive`, without touching the working tree."""
    import io
    import tarfile

    data = git("archive", tag, ".agents", repo=root, binary=True)
    with tarfile.open(fileobj=io.BytesIO(data)) as archive:  # type: ignore[arg-type]
        archive.extractall(into, filter="data")
    return into / ".agents"


def _body(path: Path) -> str | None:
    """A file's content with any frontmatter removed: what a line comparison across layouts reads."""
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8", errors="replace")
    return B.split_frontmatter(text)[1] if path.suffix == ".md" else text


def _lines(path: Path) -> set[str]:
    return {line for line in (_body(path) or "").split("\n") if line.strip()}


# Where a file of a bundle from before 0.0.22 lives now. Every path not listed stayed where it was.
PATH_MAP = {
    "roadmap.md": ["meta/roadmap.md"],
    "references.md": ["sources/references.md"],
    "layout.md": ["sources/layout.md"],
    "method/prompt-sync.md": ["meta/method/prompt-sync.md"],
    "method/prompt-merge.md": ["meta/method/prompt-merge.md"],
    "method/changelog.md": ["meta/archive/method-changelog.md"],
    "method/prompt-context.md": [".agents/method/prompt-context.md", "meta/method/home.md"],
    "knowledge/README.md": [".agents/knowledge/README.md", "sources/README.md"],
    "knowledge/INDEX.md": [".agents/knowledge/INDEX.md", "sources/templates/INDEX.md"],
}


def home_counterparts(rel: str, root: Path = ROOT) -> list[Path]:
    """The home files that hold what `rel` held in a bundle from before 0.0.22."""
    if rel in PATH_MAP:
        return [root / p for p in PATH_MAP[rel]]
    if rel.startswith("knowledge/notes/"):
        name = rel.rsplit("/", 1)[-1]
        return sorted((root / "sources/notes").glob(f"*/{name}")) + sorted((root / ".agents/knowledge/notes").glob(f"*/{name}"))
    if rel.startswith("knowledge/areas/"):
        return [root / ".agents" / rel, root / "sources/templates/areas" / rel.rsplit("/", 1)[-1]]
    if rel.startswith("tracking/"):
        return [root / "meta" / rel]
    return [root / ".agents" / rel]


def lost(base: Path, snapshots: dict[str, Path], root: Path = ROOT) -> list[tuple[str, str, str]]:
    """Every non-blank line a carrier added over the release it holds that the home does not hold.

    The home is read across its whole layout (`.agents/`, `meta/`, `sources/`), so a line that moved
    to the full notes or the release records is found where it went.
    """
    missing = []
    for name, tree in snapshots.items():
        for rel in B.all_files(tree):
            if B.is_carrier_owned(rel) and not rel.startswith("tracking/"):
                continue
            added = _lines(tree / rel) - _lines(base / rel)
            present = set().union(*(_lines(p) for p in home_counterparts(rel, root))) if added else set()
            missing += [(name, rel, line) for line in sorted(added - present)]
    return missing


def _outbox_rows(tree: Path, base: Path | None) -> dict[str, list[list[str]]]:
    """The rows a carrier offers: its outbox, or on the old layout, the tracking rows added over its release."""
    rows = {"candidates": [], "experiments": []}
    for key, rel, header in (("candidates", "tracking/candidates.md", CANDIDATES_HEADER),
                             ("experiments", "tracking/experiments.md", EXPERIMENTS_RUN_HEADER)):
        found = read_table(tree / rel, header, prefix=True)
        if base is not None:
            known = {tuple(r) for r in read_table(base / rel, header, prefix=True)}
            found = [r for r in found if tuple(r) not in known]
        rows[key] = found
    return rows


def gather(repos: list[Path], out: Path, root: Path = ROOT) -> dict:
    """Phase 1, read-only: every carrier against the release it holds; its offered rows; what it forked."""
    import json
    import shutil

    names = _names(repos)
    if out.exists() and (not out.is_dir() or (any(out.iterdir()) and not (out / GATHER_MARKER).exists())):
        raise RefusedError(f"{out}: exists and is not a previous gather's output; give it a new or empty folder")
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / GATHER_MARKER).write_text("written by release.py gather; the whole folder is replaced by the next one\n")
    available = set(tags(root))
    report: dict = {"carriers": {}}
    lines = [f"# Gather — {len(repos)} carriers", ""]
    for repo, name in zip(repos, names):
        snapshot = out / "carriers" / name / ".agents"
        shutil.copytree(repo / ".agents", snapshot, ignore=shutil.ignore_patterns("__pycache__"))
        version = installed_version(snapshot)
        legacy = B.is_legacy(snapshot)
        base = None
        if version and f"v{version}" in available:
            place = out / "base" / version
            base = place / ".agents" if place.exists() else extract(f"v{version}", place, root)
        entry = {"version": version, "legacy": legacy, "base": str(base) if base else None}
        entry["forked"] = [] if legacy else B.check_local(repo)
        entry["lost"] = [f"{rel}: {line[:120]}" for _, rel, line in lost(base, {name: snapshot}, root)] if legacy and base else []
        entry["rows"] = _outbox_rows(snapshot, base if legacy else None)
        report["carriers"][name] = entry
        rows = entry["rows"]
        lines += [f"## {name} — holds {version or 'an unknown version'}" + (" (layout before 0.0.22)" if legacy else ""), "",
                  f"- base: {'tag v' + version if base else 'none: no release tag for this version; compare by hand'}",
                  f"- offers {len(rows['candidates'])} candidates and {len(rows['experiments'])} experiment runs",
                  *[f"- changed what only a release writes: {p}" for p in entry["forked"]],
                  *[f"- added over its release, and not in the home: {p}" for p in entry["lost"]], ""]
    (out / "gather.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    (out / "gather.md").write_text("\n".join(lines), encoding="utf-8")
    return report


def slug_of(cell: str) -> str:
    """The slug a candidate row names: its first word, without markup; `extends x` names note x."""
    text = re.sub(r"[`*]", "", cell).strip()
    text = text.removeprefix("extends ").strip()
    return re.split(r"\s+[—-]\s+|\s", text, maxsplit=1)[0].strip(".,:;").lower()


def intake(out: Path, version: str, root: Path = ROOT) -> dict:
    """The gathered rows into the home's records: new candidates queued, duplicates named, runs logged.

    A candidate whose slug the queue, the history or a note already holds is not queued twice; it is
    listed so the release can add it to that row as another occurrence, which is what admission counts.
    """
    import json

    report = json.loads((out / "gather.json").read_text(encoding="utf-8"))
    queue_path, runs_path = root / "meta/tracking/candidates.md", root / "meta/tracking/experiments.md"
    queued = {slug_of(r[0]) for r in read_table(queue_path, CANDIDATES_HEADER, prefix=True)}
    history = (root / "meta/tracking/history.md").read_text(encoding="utf-8") if (root / "meta/tracking/history.md").is_file() else ""
    notes = {p.stem for p in (root / "sources/notes").rglob("*.md")}
    result = {"queued": [], "duplicates": [], "runs": 0, "taken": {}}
    new_rows, new_runs = [], []
    for name, entry in report["carriers"].items():
        taken = result["taken"].setdefault(name, [])
        for row in entry["rows"]["candidates"]:
            slug = slug_of(row[0])
            taken.append(_row(row))
            if slug in queued or slug in notes or f"`{slug}`" in history:
                result["duplicates"].append(f"{name}: {slug} (already {'a note' if slug in notes else 'queued or answered'})")
                continue
            queued.add(slug)
            new_rows.append(_row([*row[:5], version]))
            result["queued"].append(slug)
        for row in entry["rows"]["experiments"]:
            taken.append(_row(row))
            new_runs.append(_row(row))
    _insert_rows(queue_path, CANDIDATES_HEADER, new_rows, at_top=False)
    _insert_rows(runs_path, EXPERIMENTS_RUN_HEADER, new_runs, at_top=True)
    result["runs"] = len(new_runs)
    (out / "intake.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return result


def _insert_rows(path: Path, header: str, rows: list[str], at_top: bool) -> None:
    if not rows:
        return
    lines = path.read_text(encoding="utf-8").split("\n")
    at = next(i for i, line in enumerate(lines) if line.startswith(header))
    end = at + 2
    while end < len(lines) and lines[end].startswith("|"):
        end += 1
    position = at + 2 if at_top else end
    path.write_text("\n".join(lines[:position] + rows + lines[position:]), encoding="utf-8")


def legacy_own_fields(tree: Path) -> dict:
    """A pre-0.0.22 carrier's own fields, read from its README and method headers, which must agree.

    Refused when two headers disagree: the conversion would otherwise have to pick one carrier's word.
    """
    fields: dict = {}
    sources = [tree / "README.md", *sorted((tree / "method").glob("prompt-*.md"))]
    seen: dict[str, tuple[str, object]] = {}
    for path in sources:
        front = B.header(path)
        if not front:
            continue
        start = front.find("\nadopted:")
        tail = B.parse_frontmatter(front[start + 1 : front.rindex("---\n")], str(path)) if start != -1 else {}
        upstream = B.field(front, "upstream")
        if upstream is not None:
            tail["upstream"] = upstream.strip("\"'")
        for key, value in tail.items():
            if key in seen and seen[key][1] != value:
                raise RefusedError(f"{path.name} and {seen[key][0]} disagree on `{key}`; settle it in the carrier first")
            seen[key] = (path.name, value)
            fields[key] = value
    own = {k: fields[k] for k in ("carrier", "adopted", "upstream", "adapted", "declined") if fields.get(k) is not None}
    own.setdefault("adapted", [])
    own.setdefault("declined", [])
    for key in ("adapted", "declined"):
        if isinstance(own[key], str):
            own[key] = [own[key]]
    dates = sorted(re.findall(r"\b20\d\d-\d\d-\d\d\b", "".join((tree / r).read_text(encoding="utf-8", errors="replace")
                                                             for r in B.all_files(tree) if r.startswith("tracking/"))))
    if dates:
        own["harvested_through"] = dates[-1]
    return own


def _dirty(repo: Path) -> list[str]:
    entries = str(git("status", "--porcelain", "-z", "--untracked-files=all", "--", ".agents", repo=repo)).split("\0")
    paths, skip = [], False
    for entry in entries:
        if skip:
            skip = False
            continue
        if len(entry) < 4:
            continue
        rel = entry[3:].removeprefix(".agents/")
        if not B.is_carrier_owned(rel):
            paths.append(rel)
        skip = entry[0] in "RC" or entry[1] in "RC"
    return paths


def splice(repo: Path, write: bool, backup: Path | None, *, root: Path = ROOT, taken: list[str] | None = None,
           allow_dirty: bool = False, scope: list[Path] | None = None) -> list[str]:
    """Phase 2 for one carrier: the release's shipped files, its own files kept, the outbox emptied of what was taken.

    Refused unless the home's `.agents/` is the tagged release, byte for byte. A carrier on the layout
    before 0.0.22 has its own fields moved into `carrier.toml`, and the files that moved out removed.
    """
    import shutil

    source, target = root / ".agents", repo / ".agents"
    if target.resolve() == source.resolve():
        return []
    if scope is not None and repo.resolve() not in [p.resolve() for p in scope]:
        raise B.OutsideWorkspaceError(f"{repo}: not a repository of this workspace; it is not this session's to write")
    version = B.bundle_version(source)
    if f"v{version}" not in tags(root):
        raise RefusedError(f"the home's bundle is {version}, which has no tag; release and tag it before carrying it")
    tagged = str(git("show", f"v{version}:.agents/{B.CHECKSUMS}", repo=root))
    if tagged != (source / B.CHECKSUMS).read_text(encoding="utf-8") or B.checksum_problems(source):
        raise RefusedError(f"the home's .agents/ is not the tagged release v{version}; carry only a tagged release")
    if write and not allow_dirty and (dirty := _dirty(repo)):
        raise B.DirtyTreeError(f"{repo}: uncommitted bundle files {dirty}; commit them or pass allow_dirty")
    legacy = B.is_legacy(target)
    own = legacy_own_fields(target) if legacy else None
    ships, present = set(B.shipped(source)) | {B.CHECKSUMS}, set(B.all_files(target))
    keep = {r for r in present if B.is_carrier_owned(r) and not (legacy and r.startswith("tracking/"))}
    actions = [f"write {r}" for r in sorted(ships, key=str.encode)]
    actions += [f"remove {r}" for r in sorted(present - ships - keep, key=str.encode)]
    actions += [f"write {B.CARRIER_FILE} (own fields moved from the old headers)"] if legacy else []
    if not write:
        return actions
    if backup is not None:
        destination = backup / repo.name / ".agents"
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(target, destination)
    for rel in present - ships - keep:
        (target / rel).unlink()
    for rel in ships:
        (target / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source / rel, target / rel)
    if legacy:
        B.write_carrier(target, own)
        B.reset_outbox(target)
    for rel in B.OUTBOX:
        if not (target / rel).is_file():
            (target / rel).parent.mkdir(parents=True, exist_ok=True)
            (target / rel).write_text(B.OUTBOX_TEMPLATES[rel], encoding="utf-8")
    if taken and not legacy:
        for rel in B.OUTBOX:
            path = target / rel
            if path.is_file():
                path.write_text("\n".join(l for l in path.read_text(encoding="utf-8").split("\n") if l not in set(taken)), encoding="utf-8")
    for folder in sorted({p.parent for p in target.rglob("*")}, key=lambda p: len(p.parts), reverse=True):
        if folder != target and folder.is_dir() and not any(folder.iterdir()):
            folder.rmdir()
    return actions


def register(repos: list[Path], date: str | None = None, root: Path = ROOT) -> None:
    """One row per carrier in `meta/tracking/carriers.md`, at the version it holds, by its stored id."""
    date = date or datetime.date.today().isoformat()
    ids = B.carrier_ids(repos)
    path = root / "meta/tracking/carriers.md"
    text = path.read_text(encoding="utf-8")
    for repo in repos:
        row = f"| {ids[repo]} | {B.bundle_version(repo / '.agents')} | {date} |"
        pattern = rf"^\| {re.escape(ids[repo])} \|.*$"
        if re.search(pattern, text, re.MULTILINE):
            text = re.sub(pattern, row, text, count=1, flags=re.MULTILINE)
        else:
            separator = "|---|---|---|\n"
            at = text.index(separator) + len(separator)
            text = text[:at] + row + "\n" + text[at:]
    path.write_text(text, encoding="utf-8")


def align(repos: list[Path], root: Path = ROOT) -> list[str]:
    """Phase 3: every carrier verifies, holds the home's release byte for byte, and is registered at it."""
    problems = []
    ids = B.carrier_ids(repos)
    reference = (root / ".agents" / B.CHECKSUMS).read_text(encoding="utf-8")
    version = B.bundle_version(root / ".agents")
    table = (root / "meta/tracking/carriers.md").read_text(encoding="utf-8")
    for repo, name in zip(repos, _names(repos)):
        tree = repo / ".agents"
        problems += [f"{name}: {p}" for p in B.verify_problems(tree)]
        if (tree / B.CHECKSUMS).is_file() and (tree / B.CHECKSUMS).read_text(encoding="utf-8") != reference:
            problems.append(f"{name}: its SHA256SUMS is not the home's {version}")
        row = re.search(rf"^\| {re.escape(ids[repo])} \| ([^|]+) \|", table, re.MULTILINE)
        if not row:
            problems.append(f"{name}: {ids[repo]} is not in meta/tracking/carriers.md")
        elif row.group(1).strip() != version:
            problems.append(f"{name}: registered at {row.group(1).strip()}, the home is at {version}")
    return problems


# --- notes and the funnel -----------------------------------------------------------------------------


def note_state(slug: str, state: str, root: Path = ROOT) -> list[str]:
    """Moves a full note between state folders, rewrites every link to it in `sources/` and `meta/`, builds."""
    if state not in NOTE_STATES:
        raise RefusedError(f"unknown state {state!r}: one of {', '.join(NOTE_STATES)}")
    found = sorted((root / "sources/notes").glob(f"*/{slug}.md"))
    if len(found) != 1:
        raise RefusedError(f"note {slug!r}: {'not found' if not found else 'in more than one state'} under sources/notes/")
    old = found[0].relative_to(root).as_posix()
    new = f"sources/notes/{state}/{slug}.md"
    if old == new:
        return []
    changes = [f"moved {old} -> {new}"]
    for path in home_files(root):
        if path.suffix != ".md":
            continue
        rel = path.relative_to(root).as_posix()
        here = new if rel == old else rel

        def visit(target: str, rel: str = rel, here: str = here) -> str | None:
            resolved = B._resolve(rel, target)
            if resolved is None or (resolved != old and rel != old):
                return None
            _, anchor = B._relative(target)
            pointed = new if resolved == old else resolved
            return B.posixpath.relpath(pointed, B.posixpath.dirname(here) or ".") + anchor

        updated, count = B._each_link(path.read_text(encoding="utf-8"), visit)
        if count:
            path.write_text(updated, encoding="utf-8")
            changes.append(f"rewrote {count} link{'s' if count > 1 else ''} in {here}")
    (root / new).parent.mkdir(parents=True, exist_ok=True)
    (root / old).rename(root / new)
    if state == "retired":
        changes.append(f"left for you: `retired_because:` (and `superseded_by:`) in {new}, and a row in meta/tracking/retired.md")
    changes += build(root)
    return changes


DISCARD_AFTER = 3


def funnel(root: Path = ROOT) -> dict:
    """How the knowledge queue moves: candidates by releases waited, experiments queued and run."""
    released = tags(root)
    order = [t[1:] for t in released]
    current = B.bundle_version(root / ".agents")
    if current and current not in order:
        order.append(current)
    rows = read_table(root / "meta/tracking/candidates.md", CANDIDATES_HEADER, prefix=True)
    waited = []
    for row in rows:
        since = row[5] if len(row) > 5 else ""
        waited.append((slug_of(row[0]), sum(1 for v in order if B.SEMVER.match(since) and B.semver_key(v) > B.semver_key(since))))
    runs = read_table(root / "meta/tracking/experiments.md", EXPERIMENTS_RUN_HEADER)
    queued = read_table(root / "meta/tracking/experiments.md", "| Note | Experiment | Cost | Would change |")
    dates = tag_dates(root)
    last = dates.get(released[-1], "") if released else ""
    return {
        "candidates": len(rows),
        "by_releases_waited": {str(k): sum(1 for _, w in waited if w == k) for k in sorted({w for _, w in waited})},
        "discard_due": sorted({s for s, w in waited if w >= DISCARD_AFTER}),
        "experiments_queued": len(queued),
        "experiments_run": len(runs),
        "experiments_run_since_last_release": sum(1 for r in runs if r and r[0][:10] > last),
    }


def triage(apply: bool, root: Path = ROOT) -> list[str]:
    """Candidates that waited `DISCARD_AFTER` releases without gaining what they lack; with `apply`, discarded."""
    due = set(funnel(root)["discard_due"])
    if not apply or not due:
        return sorted(due)
    path = root / "meta/tracking/candidates.md"
    lines = path.read_text(encoding="utf-8").split("\n")
    kept, gone = [], []
    for line in lines:
        cells = split_row(line) if line.startswith("| ") else []
        if cells and len(cells) >= 6 and slug_of(cells[0]) in due:
            gone.append(f"| `{slug_of(cells[0])}` | **discarded**: waited {DISCARD_AFTER} releases without gaining what it lacked ({cells[2]}) |")
        else:
            kept.append(line)
    path.write_text("\n".join(kept), encoding="utf-8")
    history = root / "meta/tracking/history.md"
    text = history.read_text(encoding="utf-8")
    head, _, rest = text.partition("\n## ")
    section = (f"## Discarded by the {DISCARD_AFTER}-release rule, {datetime.date.today().isoformat()}\n\n"
               "| Candidate | Where it went |\n|---|---|\n" + "\n".join(gone) + "\n\n")
    history.write_text(head + "\n" + section + ("## " + rest if rest else ""), encoding="utf-8")
    return sorted(due)


# --- command line ---------------------------------------------------------------------------------


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="release.py", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True, metavar="COMMAND")
    p = sub.add_parser("build", help="the generated knowledge and SHA256SUMS, from sources/")
    p.add_argument("--check", action="store_true", help="compare instead of writing; exit 1 on any difference")
    p = sub.add_parser("release", help="version and date into the README, then build; prints the tag command")
    p.add_argument("version", metavar="X.Y.Z")
    sub.add_parser("check", help="the home's CI: verify, build --check, privacy and links of meta/ and sources/, budgets")
    p = sub.add_parser("gather", help="phase 1: each carrier against its release tag (writes only --out)")
    p.add_argument("repos", nargs="*")
    p.add_argument("--out", required=True)
    p = sub.add_parser("intake", help="a gather's offered rows into meta/tracking/")
    p.add_argument("out")
    p.add_argument("--version", help="the release the new candidates enter the queue at (default: the home's)")
    p = sub.add_parser("lost", help="lines a carrier added over its release that the home does not hold")
    p.add_argument("base", help="the release's .agents, as gather extracted it")
    p.add_argument("snapshots", nargs="+", help="gather's carriers/<name>/.agents folders")
    p = sub.add_parser("splice", help="phase 2: the tagged release into each carrier, its own files kept")
    p.add_argument("repos", nargs="*")
    p.add_argument("--write", action="store_true")
    p.add_argument("--backup")
    p.add_argument("--taken", help="a gather folder whose intake.json names the outbox lines to remove")
    p.add_argument("--allow-dirty", action="store_true")
    p = sub.add_parser("register", help="the carriers table, by stored carrier id")
    p.add_argument("repos", nargs="*")
    p = sub.add_parser("align", help="phase 3: every carrier on the home's release")
    p.add_argument("repos", nargs="*")
    p = sub.add_parser("note-state", help="move a full note between states, links rewritten, then build")
    p.add_argument("slug")
    p.add_argument("state", choices=NOTE_STATES)
    p = sub.add_parser("report", help="sizes, budgets and the knowledge funnel")
    p.add_argument("--check", action="store_true", help="also fail when a budget is crossed")
    p = sub.add_parser("triage", help="candidates due for discard; --apply-discards moves them to history")
    p.add_argument("--apply-discards", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:  # noqa: C901, PLR0911, PLR0912 -- one branch per command
    import json
    import tempfile

    args = _parser().parse_args(argv)
    try:
        if args.command == "build":
            lines = build(ROOT, check=args.check)
            for line in lines:
                print(("  x " if args.check else "") + line)
            if args.check:
                print("build: up to date" if not lines else f"build: {len(lines)} problems")
                return 1 if lines else 0
            print(f"build: {len(lines)} files changed; SHA256SUMS written")
            return 0
        if args.command == "release":
            print(f"released {args.version}; now commit, then tag it:\n  {release(args.version)}")
            return 0
        if args.command == "check":
            problems, notes = check(ROOT)
            for line in notes + [f"  x {p}" for p in problems]:
                print(line)
            print("home check: " + ("passed" if not problems else f"{len(problems)} problems"))
            return 1 if problems else 0
        if args.command == "gather":
            scope = B.workspace(args.repos)
            for line in B._scope_report(scope, "gathered"):
                print(line)
            gather(scope.repos, Path(args.out))
            print(Path(args.out) / "gather.md")
            return 0
        if args.command == "intake":
            result = intake(Path(args.out), args.version or B.bundle_version(ROOT / ".agents"))
            for line in result["duplicates"]:
                print(f"  ! already known: {line}")
            print(f"intake: {len(result['queued'])} candidates queued, {result['runs']} experiment runs logged")
            return 0
        if args.command == "lost":
            snapshots = [Path(s) for s in args.snapshots]
            missing = lost(Path(args.base), dict(zip(_names([s.parent for s in snapshots]), snapshots)))
            for name, rel, line in missing:
                print(f"  x {name} {rel}: {line[:120]}")
            print(f"{len(missing)} lines lost")
            return 1 if missing else 0
        if args.command == "splice":
            scope = B.workspace(args.repos, writing=args.write)
            _names(scope.repos)
            backup = (Path(args.backup) if args.backup else Path(tempfile.mkdtemp(prefix="bundle-backup-"))) if args.write else None
            taken = json.loads((Path(args.taken) / "intake.json").read_text())["taken"] if args.taken else {}
            for line in B._scope_report(scope, "written"):
                print(line)
            for repo in scope:
                actions = splice(repo, args.write, backup, taken=taken.get(repo.name), allow_dirty=args.allow_dirty, scope=scope.repos)
                if not actions:
                    print(f"{repo.name}: the home itself, left alone")
                    continue
                print(f"{repo.name}: {'spliced' if args.write else 'would splice'} {sum(a.startswith('write') for a in actions)} files, "
                      f"remove {sum(a.startswith('remove') for a in actions)}" + (f" (backup {backup})" if args.write else ""))
            return 0
        if args.command == "register":
            scope = B.workspace(args.repos, writing=True)
            register(scope.repos)
            print(f"registered {len(scope)} carriers in meta/tracking/carriers.md")
            return 0
        if args.command == "align":
            scope = B.workspace(args.repos)
            for line in B._scope_report(scope, "aligned"):
                print(line)
            problems = align(scope.repos)
            for problem in problems:
                print("  x " + problem)
            print(f"{len(scope)} carriers " + ("aligned" if not problems else f"NOT aligned: {len(problems)} problems"))
            return 1 if problems else 0
        if args.command == "note-state":
            for line in note_state(args.slug, args.state) or [f"{args.slug} is already {args.state}; nothing changed"]:
                print(line)
            return 0
        if args.command == "report":
            data = B.report(ROOT / ".agents")
            print(B.report_markdown(data))
            print("## Funnel\n\n" + json.dumps(funnel(ROOT), indent=2))
            problems = B.budget_problems(ROOT / ".agents", data)
            for problem in problems:
                print("  x " + problem)
            return 1 if args.check and problems else 0
        if args.command == "triage":
            due = triage(args.apply_discards)
            verb = "discarded" if args.apply_discards else "due for discard"
            print(f"{len(due)} candidates {verb}" + (": " + ", ".join(due) if due else ""))
            return 0
    except (BuildError, RefusedError, B.NotACarrierError, B.OutsideWorkspaceError, B.DirtyTreeError,
            B.UndeclaredScopeError, B.FrontmatterError) as error:
        print(f"  x {error}")
        return 2
    return 2


if __name__ == "__main__":
    sys.exit(main())
